### ISSUE TITLE
Не могу разобраться с svg

### ISSUE THREAD

**Issue by akhalizev** [CSSSR/csssr-project-template#101]
Добрый день. 
Вижу несколько тем с svg, но со своим вопросом так и не разобрался.
На localhost работает отображение иконок `use(xlink:href='/assets/images/icon.svg#icon_#{iconName}')`, а если делать дистрибутив, то не работает.
В моем случае иконки - файлы box.svg и checked.svg
Уже везде куда можно поместил мои svg иконки, но не видит их страница.

**Comment by felixexter** [comment]
В папке `dist` лежит этот файл `/assets/images/icon.svg`?

**Comment by akhalizev** [comment]
Да, лежит, его не трогал.

**Comment by felixexter** [comment]
Если хостишь на гитхабе, то путь должен быть относительно страницы, а не от корня.

**Comment by akhalizev** [comment]
Не понял. Вот у меня index.html. В этой же директории папка assets/images. В ней все svg. Запускаю index.html - путь же вроде правильный?

**Comment by felixexter** [comment]
Конкретно для иконки путь укажи не от корня `/assets/images/icon.svg`, а локальный `assets/images/icon.svg` без слэша в начале.

**Comment by jt3k** [comment]
@akhalizev открой /assets/images/icon.svg в браузере. Не ругается на ошибками-xml ?

**Comment by akhalizev** [comment]
Слэш убрал, заработало везде, кроме хрома.

**Comment by dzhiriki** [comment]
Если открывать файл локально (через file://), то свг в хроме не подгружается. Это не баг шаблона, а _особенность_ хрома.
Но проверять страницы локально и не стоит, это плохое решение по многим причинам.

**Comment by AdreeUA** [comment]
Решил чтобы не создавать новый пост, сюда написать... 
У меня почему-то не работает svg спрайт, в папке icons есть иконки(рабочие, проверял), но вот уже в dist не работает, в браузере открывается и ничего... куда смотреть, что делать?

**Comment by iamstarkov** [comment]
@AdreeUA вкладку Network в DevTools, посмотреть куда уходит реквест

**Comment by sneizdecker** [comment]
@AdreeUA, как вариант, можно попробовать пропустить все иконки через https://icomoon.io/ перед созданием спрайта. Мне помогло.

**Comment by AdreeUA** [comment]
@iamstarkov можешь подробней объяснить что я должен увидеть там, на что обратить внимание?

@sneizdecker Почему-то этот сервис не распознает мои иконки... На компьютере открываются во всех браузерах

**Comment by iamstarkov** [comment]
@AdreeUA посмотреть загружаются ли они вообще в браузере

**Comment by AdreeUA** [comment]
@iamstarkov Сам файл загружается, просто если открыть этот спрайт то он получается битый, ну или еще что-то... Если открыть его в текстовой редакторе, то вроде все нормально ...

**Comment by in-in** [comment]
@AdreeUA вангую width у иконки указана?

**Comment by AdreeUA** [comment]
```
 <svg xmlns="http://www.w3.org/2000/svg" style="width:0; height:0; visibility:hidden;">
    <symbol id="icon_cake" viewBox="0 0 78 76">
       <image xlink:href=....

```
Я так понимаю что тут надо указывать или в самих стилях?

**Comment by in-in** [comment]
@AdreeUA В CSS

**Comment by dzhiriki** [comment]
@AdreeUA `<image xlink:href=....` эта часть намекает на то, что у вас там дальше не svg, а png \ jpg в base64. Поэтому спрайт и не отображается.

**Comment by AdreeUA** [comment]
@dzhiriki получается что в макете у меня не svg файлы? просто когда я открываю иконки в иллюстраторе, то ведут они как вектор... Первый раз решил попробовать использовать svg, а получаться не svg =)

**Comment by dzhiriki** [comment]
Возможно, некорректно экспортировали.
