### ISSUE TITLE
sourcemap rupture

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#103]
![](https://i.imgur.com/GMkSiOV.png)

При использовании руптуры сорцмап указывает на руптуровский миксин .
Хотелось бы чтобы он указывал на место до миксина. (нужно найти возможность это сделать)

потомучто сам миксин выглядит всегда одинаково
![](https://i.imgur.com/TxmLwiy.png)

**Comment by iamstarkov** [comment]
мб, стоит открыть ишью в репо руптуры?

**Comment by jt3k** [comment]
Для этого нужно сначала определить возможность "заблекбоксить" миксин при помощи галпа. 
Есть тут знатоки в этой теме?
