### ISSUE TITLE
Как правильно миксовать?

### ISSUE THREAD

**Issue by AdreeUA** [CSSSR/csssr-project-template#104]
Столкнулся с такой ситуацией: у меня есть блок Navigation, в нем миксин который  принимает JSON файл с названиями и url самой навигации, модификатора active если он есть. Так вот такая навигация есть в шапке и в футере, только с разными падингами и небольшими декоративными отличиями. Как мне сделать миксы отдельно для футера и хедера? Ведь я только могу примиксовать елемент к самой навигации , а вот к элементам навигации не получается. Можно сделать это как-то подручными средствами или это не возможно в связи со спецификацией Jade

**Comment by kuflash** [comment]
Если нужно чтобы элементы навигации имели разные стили в зависимости от расположения на странице, то нужно использовать модификаторы. Сделай для блока navigation два модификатора. И в зависимости от этого мода меняй стили у элементов блока navigation

**Comment by AdreeUA** [comment]
Есть вот такой код
```
mixin navigation(navList)
	+b('ul').navigation&attributes(attributes)
		each item in navigation
			if item.block
				+e("li").item
					+e("a").link(href="#{item.url}")
						| #{item.block}
					if item.mod
						+navigation(item.mod)
			else if item.mod
				+e("li").item
					+logo.navigation__logo
//За код не ругайте если что, JS знаю на базовом уровне =)
```
И JSON файл:
```
[
  {
    "block": "Menu",
    "url": "/menu.html"
  },
  {
    "block": "Our story",
    "url": "/story.html"
  },
  {
    "mod": "logo"
  },
  {
    "block": "Offer",
    "url": "/offer.html"
  },
  {
    "block": "Contact",
    "url": "/contact.html"
  }
]
```
Там еще инклюдиться Logo, который вставляется в середину меню

Как мне тут сделать модификаторы, т.к. если я напишу в самом миксе то они будут видны везде и футере, и в хедере, что я думаю не очень хорошо...

**Comment by kuflash** [comment]
Вот так при использовании миксина:
```
+ navigation(data)._type_header
+ navigation(data)._type_footer
```

**Comment by AdreeUA** [comment]
А для стилизации элементов навигации использовать каскад?

**Comment by kuflash** [comment]
Да, модификаторы для этого и существуют :)

**Comment by kandrianov** [comment]
Если последняя версия bemto (1.0.2), вместо +b('ul').navigation пишите +b.UL.navigation, а элемент - +e.item (обернется в li сам). Можно и блок замиксовать: + navigation(data).footer__. Каскад от модификаторов блока - это нормально.

**Comment by AdreeUA** [comment]
Спасибо, разобрался!

**Comment by in-in** [comment]
Почему в этой строчке `each item in navigation`  navigation, а не navList? Так тоже можно?

**Comment by AdreeUA** [comment]
``` each item in navList ``` должно быть, просто я когда пример писал в одном месте поменял, а во втором нет

**Comment by solarHirdi** [comment]
Подскажите, пожалуйста, как у вас принято оформлять файловую структуру для блока с модификатором?
Как это описано здесь: https://ru.bem.info/method/filesystem/ ?
```
block/
    block.jade
    block.styl
    _modificator/
        block_modificator.styl
```
Или можно все в одну папку покидать?
```
block/
    block.jade
    block.styl
    block_modificator.styl
```

**Comment by in-in** [comment]
Всё в один файл
https://github.com/CSSSR/csssr-project-template/blob/demo/app/blocks/felixexter/felixexter.styl

**Comment by solarHirdi** [comment]
Шикарно! Спасибо.
