### ISSUE TITLE
Не запускается пересборка при измении данных

### ISSUE THREAD

**Issue by zoxon** [CSSSR/csssr-project-template#105]
Если попытаться изменить любой json файл в папке `app/data` gulp никак на это не реагирует.

**Как воспроизвести баг:**
Отредактировать любой json файл в папке `app/data`

**Что не работает:**
Переборка jade при изменении data файлов

**Как это должно работать:**
- Должна запустится компиляция jade (частичная или полная)
- В браузере должна обновится страница

**Примечание**
Думаю это из-за `gulp-cached`
`tasks/templates.js:22`

**Comment by jt3k** [comment]
да, есть [такая проблема](https://github.com/CSSSR/csssr-project-template/issues/94). 
просто пересохраняй джейд файл в котором юзается json

позже возможно будем вотчить и жсоны в папке дата, и жсоны в папке блоков
