### ISSUE TITLE
Верстка писем

### ISSUE THREAD

**Issue by justty** [CSSSR/csssr-project-template#106]
Отличный шаблон. Расскажите как вы верстаете письма? Как понимаю там своя атмосфера (табличные миксины, инлайнер, загрузчик картинок на ftp).

**Comment by felixexter** [comment]
Такие вопросы стоит задавать на stackoverflow или тостер. [Ознакомьтесь](https://github.com/CSSSR/csssr-project-template/blob/master/contributing.md), прежде чем писать.
