### ISSUE TITLE
svg

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#108]
В стилях контейнеру где svg задаю ширину и высоту чтобы было как надо. 
```
.my-style svg
  width 16px; height 16px;
```
НО При использовании svg4everybody как полифил  я кратковременно вижу svg изображение в большом размере(оригинальная картинка имеет размер 500х500).

Это происходит при загрузке страницы и очень заметно.

Это как-то можно исправить ?

**Comment by felixexter** [comment]
Обнули размеры в теге `height="0" width="0"`.
P.S. [Вопрос](https://github.com/CSSSR/csssr-project-template/blob/master/contributing.md#Вопрос) по вёрстке следует задавать на stackoverflow.com или toster.ru.
