### ISSUE TITLE
Не генерируются спрайты

### ISSUE THREAD

**Issue by MrChe** [CSSSR/csssr-project-template#110]
Все сделал как прописано, создал папку sprites в ней еще папки с картинками, в консоли происходит на постой ошибки
[14:54:51] Starting 'sprites'...
[14:54:55] Error in 'sprites' task
Invalid file signature

**Comment by jt3k** [comment]
есть рабочий пример ? :)
в путях нет русских символов ?

**Comment by felixexter** [comment]
https://toster.ru/q/221664

**Comment by MrChe** [comment]
На примере выглядит так
app/sprites/items/item1.png item2.png
и выдает данную ошибку 
[14:54:51] Starting 'sprites'...
[14:54:55] Error in 'sprites' task
Invalid file signature

По поводу подсказки с тостера так и не понял что нужно в таске добавить конкретно, и где, расширение в таске прописано ведь, файлов левых не создается, на версии шаблона 0.24 все ок!

**Comment by jt3k** [comment]
@MrChe 
посмотрите видео про гальп от ильи кантора. Особенно ту часть где он показывает как дебажить гальп.

после этого узнайте  какой из пнг-файлов  не имеет пнг-сигнатуры (это первые несколько байт файла). и почините.

Проблема в одном из файлов картинок.  К данному шаблону  не относится. Сорри.
