### ISSUE TITLE
Необходимо допилить документацию насчёт js

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#111]
Пункты документации которых мне сейчас не хватает:
- [ ] Использование js-модулей
- [ ] Если использовать нужно через npm то как юзить то, чего в npm нет? :) например [spinjs](https://github.com/fgnass/spin.js)

Предлагаю в вебпак-конфиг к путям  поиска модулей добавить глоб который будет искать модули так же в app/blocks/**

**Comment by iamstarkov** [comment]
второй пункт: `npm i -S fgnass/spin.js`

**Comment by iamstarkov** [comment]
первый пункт и про глобы не понял

**Comment by jt3k** [comment]
Я предположил, что раз уж в нашем вебпак-конфиге существует [вот такой массивчик](https://github.com/CSSSR/csssr-project-template/blob/master/webpack.conf.js#L41-L43), то неплохо было бы добавить к нему папку с js-файлами из папки blocks

Если при этом можно будет делать вот так
```javascript
import myModule from 'my-module'; // то есть без пути
```
то было бы збц.

**Comment by felixexter** [comment]
Совсем без пути плохая идея, потому что модули могут совпадать названиями из блоков и node_modules.

**Comment by jt3k** [comment]
с путями было бы тоже отлично.

лучше чем  вот так:
```
import gg from '../blocks/myblock/myblock.js';
//которое не работает ни так
import hh from '../../blocks/myblock/myblock.js';
//и нащупать верный относительный путь к модулю получается далеко не с первого раза.
```

Гораздо лучше если будет вот так
```
import myBlock from 'my-block/index.js';
```
то есть адресация в import относительно папки blocks

**Comment by felixexter** [comment]
Можно добавить только папку `blocks` и тогда подключать можно будет вот так:
```js
import block from 'blocks/block';
```

**Comment by dzhiriki** [comment]
https://www.npmjs.com/package/blocks
Тоже может сломаться :D

**Comment by felixexter** [comment]
Можно пренебречь этим модулем. Не думаю, что в обычной вёрстке он пригодится когда-нибудь.

**Comment by felixexter** [comment]
В крайнем случае всегда можно поменять, если такая необходимость будет.

**Comment by jt3k** [comment]
о! ещё вариантик
```
import block from './blocks/my-block';
```

**Comment by Nitive** [comment]
@felixexter подозреваю, что webpack-npm-install-plugin начнет его устанавливать.
Вариант `import block from '/my-block'` никак не используется.
Не знаю только, как настроить.

**Comment by felixexter** [comment]
Было бы неплохо через `/`.

**Comment by iamstarkov** [comment]
@jt3k  а в чём изначальная проблема с путями?

**Comment by kandrianov** [comment]
Лучше resolve.root использовать https://webpack.github.io/docs/configuration.html#resolve-root
Сначала модуль ищется по resolve.root, потом resolve.modulesDirectories, потом resolve.fallback.

**Comment by jt3k** [comment]
@iamstarkov проблемы с путями у меня уже нет.
Но чтобы разобраться мне пришлось помучаться.
еле нащупал вот такую комбинацию используя её в app/blocks/app.js
```js
import lolo from '../blocks/lolo/initSpinner.js';
```
и такую в джаваскрипте из папки blocks/<имя блока>/
```
import page from '../page/page.js';
```
Проблему усугубляет тот момент  что лайфрелоад срабатывает до того как  результирующий js-файл  сохранится..  
То есть после сохранения js в редакторе приходиходилось дополнительно релоадить страницу. Но понял я это не сразу.

Нужно починить документировать в ридмишечке или ещё где-то.

**Comment by jt3k** [comment]
Кстати ещё одна проблема с жсом -- 
Если я добавляю новые жс-файлы, то мне приходится перезапускать шаблон.

P.S. Я использую версию двухнедельной давности.  но думаю там на счёт этого мало-что изменилось с тех пор.

**Comment by iamstarkov** [comment]
@jt3k я думаю насчёт невотчимости свеже добавленных файлов можно обратиться в репо соответсвующему вотчеру [npm start](https://github.com/CSSSR/csssr-project-template/blob/master/package.json#L20) -> [gulp default, watch](https://github.com/CSSSR/csssr-project-template/blob/master/tasks/default.js#L12) -> [gulp watch](https://github.com/CSSSR/csssr-project-template/blob/master/tasks/watch.js#L4) ->
[gulp-watch](https://github.com/floatdrop/gulp-watch)

**Comment by Nitive** [comment]
Там js вебпаком вотчится, так что скорей в репу вебпака.
@jt3k Не смог повторить проблему, добавил файл, импортировал его и js пересобрался.

**Comment by Ivanopalas** [comment]
Не получается импортировать js. Создал js далее импортировал его > import first from '../blocks/first/first.js'; и все равно не  работает( Ничего не выводит в консоль. В чем причина?

**Comment by iamstarkov** [comment]
@Ivanopalas без стектрейса никто не поможет. ещё лучше было бы выложить свой проект на гитхаб, чтобы можно было смотреть, что именно и как не работает

**Comment by Ivanopalas** [comment]
@iamstarkov Скачал новую версию сборщика и все чудесно заработало. То судя по всему на старой версии были траблы

**Comment by jt3k** [comment]
Опять проблемы с модулями.
установил модуль `npm i -S digitalBush/jquery.maskedinput`

в жсе пишу 
```
import 'jquery.maskedinput';
```

в консоли браузера вижу  `Uncaught Error: Cannot find module "jquery.maskedinput"`

Что опять с этими нпм модулями и бабелем ?

**Comment by dzhiriki** [comment]
У `jquery.maskedinput` не прописан `main` в `package.json`, поэтому вебпак (и любые прочие) не знаю что нужно импортировать. А значит, нужно указывать путь до файла внутри модуля.

**Comment by jt3k** [comment]
спс. чтобы заработало потребовалось перезапустить сборку... хм.. Хз, во

**Comment by iamstarkov** [comment]
@jt3k пришли пуллреквест `jquery.maskedinput` c фиксом для поля `main`
