### ISSUE TITLE
Как подключить postcss-modules?

### ISSUE THREAD

**Issue by zjoin** [CSSSR/csssr-project-template#113]
Есть у кого пример конфига? Не разобраться как правильно это сделать.

**Comment by dzhiriki** [comment]
Мы его не используем, поэтому пример дать не сможем.

В документации postcss-modules есть пример интеграции с [Jade](https://github.com/outpunk/postcss-modules#pug-ex-jade).
Если вкратце: обрабатываем каждый файл стилей отдельно (в шаблоне всё собирается в один и только потом обрабатывается), затем для каждого файла стилей создаем свой json-файл с классами, подключаем этот json-файл в Jade и используем.

В целом, подключение с нашим шаблоном ничем не отличается от подключения с любым другим аналогичным стеком. Поэтому вопрос не имеет отношения к самому шаблоне и поэтому просьба задавать такие вопросы на [stackoverflow.com](http://stackoverflow.com/) или [toster.ru](https://toster.ru/), которые как раз и рассчитаны на подобные вопросы.

**Comment by in-in** [comment]
@dzhiriki Кстати, почему не используете postcss? Мне кажется, концептуально он подходит для шаблона — модульность и всё такое, подключать только нужные плагины.

**Comment by dzhiriki** [comment]
Если рассматривать вопрос как «postcss + stylus», то пользуем, но из всего нужного нам нужен лишь автопрефиксер. Правда, используется он как стороннее решение, а не как плагин для postcss. Но ничего не мешает добавить каких-то своих модулей, если они кажутся полезными и нужными в проекте.
Если «postcss взамен stylus», то планируем на него перейти, когда [SugarSS](https://github.com/postcss/sugarss) релизнется и закроет свои основные баги. В CSSSR любят легкий синтаксис стайлуса.

**Comment by in-in** [comment]
Круто! Да, имел в виду режим «postcss взамен stylus». Товарищ Ситник пушит свои проекты как бульдозер, поэтому, думаю, ждать не долго.
