### ISSUE TITLE
Подключение сторонних стилевых библиотек

### ISSUE THREAD

**Issue by MrChe** [CSSSR/csssr-project-template#117]
Какой путь прописать что бы подключать сторонние библиотеки такие как jeet,nib в главный стилевой файл app.styl, если прописать @import 'jeet' то в консоли выскакивает ошибка
failed to locate @import file jeet.styl

Ответ
  На данный момент нужно импортировать данные либы только из папки node_modules

**Comment by yakhinvadim** [comment]
@MrChe Посмотри тут, может помочь: https://github.com/CSSSR/csssr-project-template/issues/67

**Comment by MrChe** [comment]
@yakhinvadim  ок посомтрю, но все же хотелось бы понять как исправить данный баг, что бы подключать данные либы как написано в доке!
