### ISSUE TITLE
Как насчёт отключить проверки кодестайла в eslint?

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#121]
Предлагаю подключить этот пресет https://github.com/blond/eslint-config-pedant
Он призван проверять только  ошибки в логике но не кодестайл.

**Comment by iamstarkov** [comment]
Думаю проверка код стайла в групповых проектах достаточно важная вещь

**Comment by jt3k** [comment]
не вижу большого смысла расставлять пробелы после ключевого слова  function

**Comment by iamstarkov** [comment]
кодстайл как раз об этом https://twitter.com/slicknet/status/717743865562681344

я могу предложить поменять в своём проекте текуший еслинт конфиг, на понравившийся

**Comment by jt3k** [comment]
что насчёт jscs форматтера ?
код будет выглядеть одинаково и безболи

**Comment by iamstarkov** [comment]
`eslint --fix`

**Comment by jt3k** [comment]
о!

**Comment by iamstarkov** [comment]
https://twitter.com/iamstarkov/status/694198237473939456

**Comment by jt3k** [comment]
надо взять на вооружение и сделать  npm таску для этого дела ;-)
