### ISSUE TITLE
npm run build не сжимает ничего

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#122]
фиксните плз

**Comment by jt3k** [comment]
упс.  пропустил  , что это делается при помощи `npm run production`

**Comment by jt3k** [comment]
хм, но хтмл всёравно не сжимается.

**Comment by iamstarkov** [comment]
если проблема всё ещё остаётся то, пере-открой ишью

**Comment by felixexter** [comment]
> хм, но хтмл всёравно не сжимается.
Так задумано.

**Comment by felixexter** [comment]
Можно добавить флаг для минификации html, если это необходимо.

**Comment by jt3k** [comment]
В конфиге или  есть ключ командной строки ?
