### ISSUE TITLE
Давайте обновим ESLint

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#123]
а то у меня конфиг pedant  не хочет заводиться https://github.com/blond/eslint-config-pedant

**Comment by Nitive** [comment]
Давай, сделаешь PR?

**Comment by jt3k** [comment]
как же я сделаю? Ведь тестов у нас нет

**Comment by Nitive** [comment]
А при чем тут тесты?
Как и зачем тестировать выдачу eslint'а?

**Comment by jt3k** [comment]
Ну допустим параметр в конфиге изменил своё название или  формат.

чтобы это задетектить нужно  протестировать все ли  правила из старого конфига сработали в новой версии еслинта.

И если что-то не  сработало то починить.

**Comment by jt3k** [comment]
ну тупо bad.js и good.js

**Comment by Nitive** [comment]
Eslint кидает варнинги, что правила переименованны. Можно смело обновляться.

**Comment by jt3k** [comment]
У меня есть предположение, что если взять эти экзамплы  https://github.com/blond/eslint-config-pedant/tree/master/examples
и прогнать  на них  наш пресет еслинта до обновления  и после обновления, то количество ошибок не будет равным.

В еслинте имена свойств и их значения постоянно меняются от версии к версии.
Простым обновлением довольно опасно апдейтить.

**Comment by Nitive** [comment]
Апдейтил на реальных проектах. Код проекта сам по себе тест.

**Comment by iamstarkov** [comment]
затухло?

**Comment by jt3k** [comment]
да чот времени не найду. Пусть повисит, вдруг кто займётся

**Comment by akilbekov** [comment]
Обновил, вроде все работает как надо.
