### ISSUE TITLE
А как поменять тег блока?

### ISSUE THREAD

**Issue by Lehakos** [CSSSR/csssr-project-template#127]
Когда у каждого блока свой миксин, получается, что блок привязан к тегу, который задан в миксине? А если, например, блок title может быть в разных местах и h2, и h3, и вообще div? Возможно ли как-то изменять тег блока при его подключении?

**Comment by azanov** [comment]
```
mixin myBlock(tagName)
  +b({ tag: tagName }) Test

+myBlock('span')

```

или

```
mixin myBlock(tagName)
  +b(tagName) Test

+myBlock('span')
```

**Документация:** https://github.com/kizu/bemto#changing-the-tag-name

**Comment by Lehakos** [comment]
Спасибо!

**Comment by jt3k** [comment]
```
+b('SPAN') lalala
+e('SPAN') lololo
```
