### ISSUE TITLE
Правильная реализация блока с помощью классов

### ISSUE THREAD

**Issue by Lehakos** [CSSSR/csssr-project-template#130]
А вы не могли бы привести пример простейшей реализации БЭМ блока с помощью ES6 класса? Как вы обычно делаете это в проектах?

**Comment by iamstarkov** [comment]
Как они связаны?

**Comment by Lehakos** [comment]
Ну мне один из сотрудников CSSSR говорил, что js блока вы пишите с помощью классов. Просто в сети мало информации по js части БЭМа без яндексового стека технологий. Интересно посмотреть ваш опыт по этой части.

**Comment by iamstarkov** [comment]
я думаю, что сделано реактом. но не берусь утверждать

**Comment by jt3k** [comment]
у меня в проектах обычно вот такое
jade:
```jade
 +b.block
  +e.one.js-one
  +e.two.js-two
```
js:
```js
const ONE_CLASS = 'js-one';
const TWO_CLASS = 'js-two';

$('.' + ONE_CLASS).text('КУЙ, ХИЗДА, ')
$('.' + TWO_CLASS).text('ДЖИГУРДА!!!');
```

Чтобы юзить что-то большее надо идти в BEM.info и учицо там
Они недавно написали кучку инструментов для того чтобы  дружить их технологии с галпами и вебпаками. А также выпустили много видосов на эту тему. Позыбри [тута](https://www.youtube.com/results?search_query=bem+%D0%B2%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80+%D0%B3%D1%80%D0%B8%D0%BD%D0%B5%D0%BD%D0%BA%D0%BE)
