### ISSUE TITLE
Назойливая проблема с JavaScript

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#138]
- Ставим и запускаем темплейт
- Идём в app/scripts/app.js и делаем ему содержимое в виде скобки `)` сохраняем, видим в терминале ошибку.
  ```/private/tmp/csssr-project-template/app/scripts/app.js
  1:1  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)

[18:46:32] Error in 'scripts' task

./app/scripts/app.js
Module build failed: SyntaxError: /private/tmp/csssr-project-template/app/scripts/app.js: Unexpected token (1:0)
> 1 | )
    | ^
  2 | 
    at Parser.pp.raise (/private/tmp/csssr-project-template/node_modules/babylon/lib/parser/location.js:22:13)

... и ещё куча таких же Parser.pp ошибок 
  ```
- Наш шаблон сломался. Изменения в js не приведут к его починке. Единственный способ сделаеть его вновь работающим - остановить gulp и сделать `npm start` снова.
- Чтобы убедиться в том, что оно больше не работает ––> делаем содержимое app.js таким `console.log('lalala');`, сохраняем и проверяем дев-консоль браузера.  Там не появится 'lalala'

**Comment by iamstarkov** [comment]
gulp-plumber?

**Comment by jt3k** [comment]
@iamstarkov я его закомментировал его в этом файле `/tasks/scripts.js:22` , и проверил это не исправило проблему.

**Comment by iamstarkov** [comment]
наоборот, он должен решать такие проблемы, если я ничего не путаю

**Comment by jt3k** [comment]
@iamstarkov плумбер это такая штука которая  модифицирует  .pipe таким образом чтобы в последующих пайпах из-за ошибки код не падал, а продожал дальше собиратся.

**Comment by pickmecoach** [comment]
Подход у меня не научный, и разобраться, что к чему не вышло. Но вот, что удивительно:
Если в вашем внешнем обработчике `(gulp-plumber-error-handler)` закомментить 
`this.emit('end');`
который как раз-таки [когда-то советовали прописывать для watch](http://blog.ibangspacebar.com/handling-errors-with-gulp-watch-and-gulp-plumber/), то все будет работать без поломок, и после устранения ошибок в коде, вотчер их подхватит.
[Дополнительная информация](https://andidittrich.de/2016/03/prevent-errors-from-breaking-gulp-watch.html)

**Comment by jt3k** [comment]
@pickmecoach  надо-бы проверить! Спасибо за исследование

**Comment by pickmecoach** [comment]
да, я думаю, это все замечали. так что в копилку

**Comment by felixexter** [comment]
привет, можно добавить опцию для отмены эмита в `gulp-plumber-error-handler`, чтобы заюзать в таске со скриптами

**Comment by jt3k** [comment]
о, давай. Просто шаблон сейчас не работает. До конца мы так и не разобрались почему. но убирание emit('end') помогает.

**Comment by mixail-novikov** [comment]
Сделал фикс, могу запилить PR
Обработку и вывод ошибок нужно перенести/реализовать в CSSSR/webpack-stats-logger

**Comment by felixexter** [comment]
@mixail-novikov было бы круто

**Comment by jt3k** [comment]
всем спасибо!
