### ISSUE TITLE
Проблемы с запуском

### ISSUE THREAD

**Issue by Rinocrosser** [CSSSR/csssr-project-template#139]
Клонирование идёт без проблем, установка уже выдаёт ошибки:
(попробовал NodeJS 4 LTS, также проходит с ошибками, да и сборке нужен >=5.1)

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fseve
> nts@1.0.12
> npm WARN optional Skipping failed optional dependency /stylint/chokidar/fsevents
> :
> npm WARN notsup Not compatible with your operating system or architecture: fseve
> nts@1.0.12
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "i"
> npm ERR! node v6.2.0
> npm ERR! npm  v3.8.9
> npm ERR! code ELIFECYCLE
> 
> npm ERR! unicode@0.6.1 postinstall: `node install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the unicode@0.6.1 postinstall script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the unicode package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs unicode
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls unicode
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     F:\Code\CSSSR\my-project\npm-debug.log

Уточню, что ставлю под Windows 8.1 x64

**Comment by Rinocrosser** [comment]
Решается установкой NodeJS строго 5.х версии.
Удалил 6.х, перезагрузился, поставил 5.11.1 запустил npm cache clean.
Теперь шаблон скачивается и устанавливается без проблем.

**Comment by in-in** [comment]
Тогда закрывай ишью

**Comment by Rinocrosser** [comment]
Эх, лучше бы в описании отметить этот нюанс по версиям. Хотя, у нас же тестовое - значит проблемы решать тоже нужно уметь! :)

**Comment by jt3k** [comment]
дык отметь плз

**Comment by artem-malko** [comment]
Может проще найти пакет, который использует unicode@0.6.1 и пофиксить там (ишью отправить). Или ишью в  unicode завести?

**Comment by Nitive** [comment]
👍 , unicode не первый раз уже досаждает.

**Comment by Nitive** [comment]
Цепочка зависимостей `gulp-svg-symbols` --> `slug` --> `unicode`

**Comment by artem-malko** [comment]
Ставьте мой форк, я там избавился от slug. 
 "gulp-svg-symbols": "https://github.com/artem-malko/gulp-svg-symbols/archive/master.tar.gz",

**Comment by in-in** [comment]
К слову, почему svg-sprite не используете? Из-за размера?
