### ISSUE TITLE
Валидация форм jQuery и доступность функций извне

### ISSUE THREAD

**Issue by riseremi** [CSSSR/csssr-project-template#140]
Привет!

Есть страницы и скрипты на этом шаблоне, их перенесли в проект на Symfony. В нём есть какие-то свои приблуды для валидации форм (подключается плагин `jquery.validate.js` и генерируется куча левого кода). Если ставить плагин через npm и включать в сборку, он не доступен снаружи для сгенерированного кода в `<script></script>`. Это из-за webpack обертки, возможно. 

Вопрос: можно ли заставить это всё работать? И в целом можно ли как-то сделать функции из собранного `app.min.js` доступными извне?

UPD: погуглил на свежую голову. Возможно, это решение https://webpack.github.io/docs/library-and-externals.html

Если кто-то уже решал это в настоящих проектах, отпишитесь, пожалуйста.

**Comment by artem-malko** [comment]
@riseremi это вопрос про webpack, а не про то, как пользоваться данным шаблоном. Я бы порекомендовал скринкаст Ильи Кантора послушать, много полезного узнаете: https://learn.javascript.ru/screencast/webpack

**Comment by iamstarkov** [comment]
непосредственно к решение проблемы доступного извне jquery http://stackoverflow.com/questions/22530254/webpack-and-external-libraries#22619421
* объявить jquery в externals
* загружать её через <script />

**Comment by riseremi** [comment]
Спасибо, изучу. Закрываю.

**Comment by iamstarkov** [comment]
+ https://github.com/petehunt/webpack-howto

**Comment by jt3k** [comment]
я иногда делаю так:
```js
// для жыкверя
global.$ = $
// для лодаша
global._ = _
```

 таким образом  переменные из модулей становятся глобальными.
