### ISSUE TITLE
Генерация блока по шаблону.

### ISSUE THREAD

**Issue by dontlemmedown** [CSSSR/csssr-project-template#145]
Наверняка во многих проектах встречаются идентичные блоки, либо с незначительными отличиями и я не про внешний вид, а про код. В лучшем случае, есть база готовых блоков, которые переходят из проекта в проект, но, не всегда же, верно? Иногда код просто дублируется (не копипаст), а именно пишется заново.

Было бы неплохо - перестать писать одно и тоже. Тем более, что это можно автоматизировать.

В данный момент - блок генерируется по [обычному шаблону](https://github.com/CSSSR/csssr-project-template/blob/master/make-block.js#L14-L17). И это универсально, но, не всегда удобно, ибо таких шаблонов можно сделать несколько и подключать при необходимости, к примеру, обычно навигация - выглядит как то так (упрощена)

``` jade
mixin menu(data)
    +b('nav').menu&attributes(attributes)
        +e('ul').items
            each item in data
                +e.item
                    +e('a')(href=item.url) #{item.title}
```

``` stylus
.menu
    display block

    &__items
        display flex
        justify-content space-between

    &__item
        padding 1em

        &_active, &:hover
            background-color #eee
            color tomato

    &__link
        color inherit
        text-decoration none
```

Это постоянно приходиться писать руками, но, имхо, было бы неплохо - задавать шаблон для генерации блока:

``` npm
npm run make-block menu -t navigation
```

А если шаблон не задан, либо задан несуществующий, то генерировать блок по дефолтному шаблону.

Таким образом - со временем будет неплохая UI база, причем, код компонентов будет выглядеть одинаково на каждом проекте, соответственно, будет проще ориентироваться в генерируемых компонентах.

Примитивный пример:
https://jsfiddle.net/vsm4opqk/

Так же - очевидным плюсом данного подхода будет возможность генерации не только jade,stylus,но и json и js (при необходимости) не меняя логику make-block.js, а лишь добавив новый json файл.

Предлагаю подобную структуру:

```
├── make-block/                  # Все файлы относящиеся к функциюналу make-block
│   ├── blocks/                  # Блоки
│   │ ├── default.json           # Блок по умолчанию
│   │ └──  anotherone.json       # Шаблон очередного блока
└── index.js                     # Инициализация (в данный момент make-block.js)
```

**Comment by jt3k** [comment]
Звучит вполне не плохо, но я не встречал в своей практике ситуацию, когда мне это было остро необходимо. Я пока испытываю больше боли, из-за того, что приходится каждый раз прописывать инклюды для новых jade-файлов  руками после создания нового блока. Но и это тоже так-себе проблемка.

**Предложения**

- Нужно уйти от формата json при хранении темлейтов в сторону js-файлов

    Чистый js добавляет гибкости:
  - комментарии
  - треугольные кавычки для нормальной многострочности в темплейтах

Внутри js-файла с темплейтом  думаю нет нужды дублировать имя темплейта в переменные. т.е. "унифицировать внутрянку темплейтов"

**на развитие:**
возможность "пушить" в общее хранилище свои шаблоны
лайкать шаблоны
делиться шаблоном в соцсетях.
комментировать

**Comment by dontlemmedown** [comment]
**Нужно уйти от формата json при хранении темлейтов в сторону js-файлов**
Да, с этим я полностью согласен.

```js
// default.js
export default blockName => ({
  template: `
     mixin ${blockName}()
        +b.${blockName}&attributes(attributes)
      	   block
  `,
  style: `
     .${blockName}
        display block
  `
});

// make-block.js
const { template, style } = require('path/to/template');
```

**на развитие**:
Ну, для этого есть PR.

**Comment by lamartire** [comment]
> Я пока испытываю больше боли, из-за того, что приходится каждый раз прописывать инклюды для новых jade-файлов руками после создания нового блока.

Мимо проходил и решил рассказать о своем костыле для решения этой проблемы.
Вероятнее всего оффтоп и меня погонят от сюда с вилами, но все же.

Решил для себя проблему так - скрипт создания блока также пишет инклюд соответствующего блока в файл `import.jade`, соответственно, так как пути для `jade` выставлены абсолютные, то надобность что-либо инклюдить отпадает вообще.

**Comment by jt3k** [comment]
слуш. Довольно годное решение! Спасибо!

**Comment by lamartire** [comment]
Пожалуйста ;)

**Comment by lamartire** [comment]
Ребята, еще раз привет.

Прочитал еще раз этот пост и стало интересно реализовать такое решение.
![block from layout](http://dl2.joxi.net/drive/2016/07/21/0016/3508/1093044/44/0dba008d2f.jpg)

Сделал на фоне своих [наработок](https://github.com/lamartire/catstruct/blob/blocks-layout/core/create-block-from-layout.js), может быть код не такой изящный, но все же, это всего лишь попытка и она уже работает, так что, не спешите кидать гнилыми помидорами ;)

Работает в принципе так:
Вводим комманду `npm run layout-block navmenu menu`, соответственно, если шаблон `menu.btpl` (block template, чтобы не путалось с другими файлами, да и визуально отличалось ото всего) существует - генерируем блок по этому шаблону, если нет - кидаем ошибку.

Пока сделал для `pug`, но для `stylus` с таким подходом не составит труда сделать тоже самое.

**з.ы.**
Также инлюдится в глобальный файл импорта.

**з.з.ы.**
Очевидный недостаток такого подхода с "инклюдингом" обстоит в производительности. Если я правильно понимаю, кеширование в таком случае не прокатит вообще, тк компилируется страница в целом подхватывая все миксины, а раз это у нас происходит, тут уже нужно или жертвовать производительностью подключая простыню из миксин или формировать для каждой страницы свой лист зависимостей, через тот же `make-block`.

**Comment by lamartire** [comment]
И снова я тут.

В общем, играться с расширениями для файлов не вариант вообще, тк с подсветкой синтаксиса гораздо проще делать шаблоны. В общем, схема таже:

![](http://i.imgur.com/iJOUcWn.jpg)

Код также не очень, но идея работает.
