### ISSUE TITLE
Предложение заменить таймстамп на хеш в параметре к стилям

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#146]
В HEAD сайта мы подключаем стили вот так:
```html
<link href="/assets/styles/app.min.css?t=1467110158137" rel="stylesheet">
```
значение параметра `t=` меняется каждый раз при сборке, и он нам здесь необходим, для того, чтобы помочь браузеру обновить кеш.

Бывают случаи, когда в изменении значения параметра `t=` нет необходимости.
Например когда в проекте меняется всего один jade-файл, гит-диф показывает все 10 мест где подключается цсс...

Предлагаю заменить в том месте таймстамп на md5-хеш, или что-нибудь более подходящее для этго.

**Comment by felixexter** [comment]
Гит-дифф показывает изменения в сборке, обычно сборка стоит в игноре, зачем её в репе хранить?

**Comment by jt3k** [comment]
Конечно папку dist в git не попадает, и  эта доработка не имеет смысла, скажете вы.

Но у нас папку дист пушим.
И да у нас ci не собирает сам ничего, а просто копирует файлы из гита.

**Comment by jt3k** [comment]
опередил :)

**Comment by felixexter** [comment]
Если нет необходимости в этом, то просто можно убрать timestamp или поставить что-то на своё усмотрение, это уже не от сборки зависит.

**Comment by jt3k** [comment]
ок.
Я просто для новых проектов всегда клонирую  цсср из этой репы. Подумал, что была бы хорошая идея добавить хеш

**Comment by jt3k** [comment]
Ну в общем если нет разницы то давай запилю ? :))

**Comment by Nitive** [comment]
Можно хеш исходников смотреть. Если это не будет ощутимо тормозить или усложнять сборку, почему бы и нет

**Comment by jt3k** [comment]
по скорости сборки просадки не дало.
Замер скорости простенький -- по данным от последнего завершённого таска в консоли.
Слева на скриншоте 2 запуска `npm run production` затем два запуска `npm run build` используя текущую сборку.
Справа то же самое только используется модификация с хешами 
![](https://i.imgur.com/PaDg3Ai.png)
По хорошему нужно прогнать много раз на бОльшем количестве больших файлов. Но думаю результат будет схожим.
