### ISSUE TITLE
Вопросы по файловой структуре

### ISSUE THREAD

**Issue by c1n1k** [CSSSR/csssr-project-template#148]
1. картинки, шрифты, складываются в папку resources?
2. сброс/normalize стилей есть?

**Comment by jt3k** [comment]
1. цсс для шрифта подключается в этом файле [app/styles/helpers/fonts.styl](https://github.com/CSSSR/csssr-project-template/blob/master/app/styles/helpers/fonts.styl)
сам шрифт можно положить например в `app/resources/fonts` (нужно создать папку самостоятельно). После компиляции шрифт окажется в `dist/assets/fonts/`

  Пример подключённого шрифта смотри в ветке `demo`:
   - Вот цсс шрифта  [demo:app/styles/helpers/fonts.styl](https://github.com/CSSSR/csssr-project-template/blob/demo/app/styles/helpers/fonts.styl) 
   - и сам шрифт [demo:/app/resources/assets/fonts](https://github.com/CSSSR/csssr-project-template/tree/demo/app/resources/assets/fonts)

2. нормалайза нет. Есть только ресет. Лежит тут [app/styles/helpers/optimize.styl](https://github.com/CSSSR/csssr-project-template/blob/master/app/styles/helpers/optimize.styl). Но нет проблемы в том чтобы добавить его самостоятельно. По образу и подобию как это сделано с ресетом(helpers/optimize) вот в этом файле [app/styles/app.styl](https://github.com/CSSSR/csssr-project-template/blob/master/app/styles/app.styl)

**Comment by jt3k** [comment]
@c1n1k зокрывай
