### ISSUE TITLE
Появились проблемы с sourcemaps в js

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#150]
Проявляется это не сразу, и  выглядит следующим образом:
- Я пишу `debugger;` в исходном коде
- В браузере срабатывает брейкпойнт.
- Брейкпойнт этот на той же строке что и в исходном файле.
- Содержимое файла где брейкпойнт принадлежит другому файлу.
- В правой панеле девтулзы я вижу, что контекст принадлежит исходному файлу.

![](https://i.imgur.com/l4OLGnC.png)

Подробности пока не расписываю т.к. мало времени и не смог выяснить закономерность.
Но появилось это после последних вмердживаний. Подозреваю, что виноват happypack или его настройки.

Если ктонить заметил подобные проблемы -- пишите сюда. будем дебажить вместе.

**Comment by Nitive** [comment]
@jt3k всё ещё воспроизводится?

**Comment by jt3k** [comment]
Давай закроем. Я пока не могу проверить -- занят Но в список дел добавил -- освобожусь проверю напишу (может быть).
