### ISSUE TITLE
Понадобилось хранение ресурсов в корне а не в assets

### ISSUE THREAD

**Issue by Badalik** [CSSSR/csssr-project-template#154]
На одном из проектов понадобилась такая прихоть. Убрал assets из путей в тасках и в миксинах. Однако такое работает только с командой npm run production, при обычном старте копируются только спрайты, иконки и стили и js

**Comment by iamstarkov** [comment]
я ничего не понял

**Comment by Badalik** [comment]
То есть нужно чтоб чтоб images, styles, fonts, scripts лежало не в assets а в корне, рядом с index файлом

**Comment by iamstarkov** [comment]
```diff
# + tasks/icons.js
# - tasks/icons.js
+ gulp.task('after', () =>
+   gulp.src('assets/').pipe(gulp.dest('dist/'))
+ )
+
- gulp.task('build', () => {
+ gulp.task('build', ['after'], () => {
```

**Comment by Badalik** [comment]
Выскакивает ошибка, но я кажется разобрался, при обычном старте все ресурсы не копируются, поэтому все правильно было
