### ISSUE TITLE
Подключение js плагинов и их использование

### ISSUE THREAD

**Issue by c1n1k** [CSSSR/csssr-project-template#158]
Понадобилось подключить всё jq плагины по отдельности, и потом вызвать их подключение в app. Как это сделать? Если библиотеку я подключил, то вот как сделать её вызов уже не пойму.

**Comment by jt3k** [comment]
"всё jq плагины по отдельности" --- не понятная формулировка.  Все плагины это  что ?

1. отдельные файлы
2. плагины установленые через npm
3. какие-то плагины в какойто определённой папке ?

"Если библиотеку я подключил" -- что Вы понимаете под словом подключил?

**Comment by c1n1k** [comment]
В html помимо `<script src="/assets/scripts/app.min.js"></script>` должно добавляться другие, например:
```
<script src="/assets/scripts/mask.js"></script>
<script src="/assets/scripts/calendar.js"></script>
<script src="/assets/scripts/wow.js"></script>
<script src="/assets/scripts/app.min.js"></script>
```
а в `app.min.js` это всё инициализироваться и тп, по старинке в общем

**Comment by jt3k** [comment]
неправильно )

в нашем шаблоне используется  модульная система.
это значит, что любой плагин подключается из неё.

Гораздо удобней установить всё через npm и подключать через import

Покажу на примере wow.js:
пишешь эту команду в папке проекта
`npm install wow.js --save`
это добавит в твой package.json  дополнительный модуль который нужен твоему приложению.  Теперь ты можешь переносить проект с  компа на комп и не  тягать за собой  зависимости (исходные файлы с wow.js ).

После этого запускай  шаблон, 
и внутри  app.js пиши
`import WOW from 'wow.js';`

после этого у тебя в переменной WOW появится сам wow.js плагин. 
Делай с ним что-хочешь.

Например:
```
var wow = new WOW(
  {
    boxClass:     'wow',      // animated element css class (default is wow)
    animateClass: 'animated', // animation css class (default is animated)
    offset:       0,          // distance to the element when triggering the animation (default is 0)
    mobile:       true,       // trigger animations on mobile devices (default is true)
    live:         true,       // act on asynchronously loaded content (default is true)
    callback:     function(box) {
      // the callback is fired every time an animation is started
      // the argument that is passed in is the DOM node being animated
    },
    scrollContainer: null // optional scroll container selector, otherwise use window
  }
);
wow.init();
```
)))

**Comment by c1n1k** [comment]
Я понимаю что это не правильно :) но вот нужно бывает именно так вот неправильно:)

Кстати, а ака правильно подключать jq плагины, допустим я установил его через npm, через import подключил `import styler from 'styler.jquery'` но когда вызываю `$('select').styler()` вылазит ошибка что styler нигде не используется.

И ещё вопрос как устанавливать такие плагины/библиотеки js если их нет npm?

**Comment by jt3k** [comment]
# 1
> Я понимаю что это не правильно :) но вот нужно бывает именно так вот неправильно:)

ну если нужно неправильно то делай неправильно (подключением всех скриптов внутри джейд-шаблона)

# 2

> как подключать жыкверь-плагины правильно
обычно достаточно просто сделать
```
import from 'pluginname';
```
после этого плагин должен быть доступен через переменную $

# 3

> как подключать жыкверь-плагины правильно если их нет в официальном нпм-репозитории

можно попробовать установить напрямую из гитхаба  командой
`npm install githubname/reponame`

Но к примеру команда `npm install Dimox/jQueryFormStyler` выдаёт ошибку (т.к. в репозетории этого плагина в секции main  файла package.json какаято чепуха  вместо правильного значения).

Поэтому можно просто скачать файл этого плагина и положить рядом с app.js

затем подключаешь этот плагин таким же способом как в пункте №2
```
import from './jquery.formstyler.js';
```

# Кроме того (внимание возможна некомпетентность)
Твой formstyler требует подключения его-css-файлов. Чтобы это сделат можно положить в app/resources/styles/ и...  воспользоваться одним из двух возможных вариантов:

- ЛИБО приинклюдить этот стиль внутри /app/styles/app.styl (смотри документацию как это  сделать правильно с css-файлами)
- ЛИБО подключить в блоке head как обычный css-файл. (путь должен быть таким: `/assets/styles/jquery.formstyler.css`)


Я не могу сказать что это единственный правильный способ, т.к. полагаю, что возможен вариант когда мы подключаем стили прям в жс, а вебпак  магическим образом превращает это в блок `<link  rel='stylesheet' href='.....'>` или во что-то ещё.  НО вариант описаный выше вполне рабочий.

**Comment by c1n1k** [comment]
как вообще подключать js из блоков?
ещё у меня не получается подключить таким образом `import from './jquery.formstyler.js';`

**Comment by jt3k** [comment]
Я заметил ошибку в своём тексте.
Если модуль ничего не возвращает из себя, то подключать его надо так:
```js
import './jquery.formstyler.js'
```
то есть **from** здесь не нужен.
----
Всё подключается относительными путями от app.js
