### ISSUE TITLE
исключения в скриптах для дев режима

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#161]
Научите пользоваться этим. Я пару раз пробовал самостоятельно научиться но всё тщетно.

Имеется в виду переменная `__DEV__`  в конструкциях типа этой:
```js
if (__DEV__) {
  window.alert('blablabla');
}
```
..Который  потом вырежется  после компиляции в production-режиме.

Интересуют  также такие переменные внутри в jade и stylus

**Comment by jt3k** [comment]
Давайте запилим и задокументируем ?

**Comment by dontlemmedown** [comment]
А чему там учиться то?

**webpack.config.js**
```js
{
	//...
  plugins: [
  	//...
    new webpack.DefinePlugin({
    	__DEV__: process.env.NODE_ENV === 'development'
    })
  ]
}
```
Соотвественно, все файлы, которые проходят через webpack имеют глобальную переменную __DEV__ со значением true/false.

Т.е это
```js
if (__DEV__) {
	// ...
}
```
в production преобразуется в
```
```js
if (false) {
	// ...
}
```

А uglifyjs вырезает такие конструкции (я про последнюю).
```

**Comment by jt3k** [comment]
всо ок. разобрался.
webpack.config.js
```js
...
			new webpack.DefinePlugin({
				// признак дев-режима для юзания в скриптах
				__DEV__: JSON.stringify(process.env.NODE_ENV !== 'production')
			})
...
```

tasks/templates.js
```js
const data = {
...
	// признак дев-режима для юзания в jade-файлах
	__DEV__: process.env.NODE_ENV !== 'production'
};
```

tasks/styles.js
```js
		.pipe(stylus({
...
			define: {
				// признак дев-режима для юзания в styl-файлах
				'__DEV__': process.env.NODE_ENV !== 'production'
			}
		})
...
```
