### ISSUE TITLE
подключение bootstrap-styl

### ISSUE THREAD

**Issue by vitstr** [CSSSR/csssr-project-template#162]
Ребята, подскажите как правильно подключить bootstrap-овский js из пакета bootstrap-styl?

Так же проблема с путями возникает при подключении styl файлов:

```
@import '../../../node_modules/bootstrap-styl/bootstrap/mixins'
```

но так как mixins содержит в себе вложенный import получаем ошибку с путями

в итоге пришлось подключать по маске

```
@import '../../../node_modules/bootstrap-styl/bootstrap/mixins/**/*'
```

пока подключил вот так в layout-default.jade но не уверен в правильности подхода..

```
+scripts(['app.min.js', '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'])
```

Спасибо.

**Comment by TryHardNinja** [comment]
Ответ на ваш вопрос возможно тут https://github.com/CSSSR/csssr-project-template/issues/160
