### ISSUE TITLE
module.js:327 throw err;

### ISSUE THREAD

**Issue by psywalker** [CSSSR/csssr-project-template#165]
В терминале вебшторма пишу команды в таком порядке:
1. npm run build - всё в порядке
2. pwd - всё в порядке
3. ls -la - всё в порядке
4. npm run build - и вот на этом этапе возникает ошибка - 
   "> csssr-project-template@0.26.0 build /Users/maks/Desktop/Ussr /ussrproject
   > gulp build

[09:13:32] Failed to load external module babel-register
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/json/stringify'
"
Ну а дальше, как на скриншоте: "https://monosnap.com/file/kCXdrMqtYIzHMYAYpmIlYynRBr3gjN"

Вопросы такие:
1. Почему возникают эти ошибки?
2. Как их исправить?
3. Эти ошибки очень критичные или нет? Хотелось бы, чтобы всё установилось правильно.

**Comment by i1yas** [comment]
Тоже хотел про это задать вопрос, у меня не собралось из коробки. Насколько понял, помогло добавление babel-runtime в dev-зависимости.  Вот тема https://github.com/yeoman/generator-webapp/issues/356 там много вариантов лечения предлагают.

**Comment by i1yas** [comment]
Тоже про это хотел вопрос задать, у меня не собралось из коробки. Пришлось добавить babel-runtime в devDependencies, вроде тогда заработало. Вот тема на всякий https://github.com/yeoman/generator-webapp/issues/356 там предлагается много разных решений.

**Comment by jt3k** [comment]
тоже сталкивался с этой проблемой, но просто не обращал на неё внимание.
