### ISSUE TITLE
fix README or add mixins

### ISSUE THREAD

**Issue by TryHardNinja** [CSSSR/csssr-project-template#167]
https://github.com/CSSSR/csssr-project-template/blob/master/app/styles/helpers/mixins.styl

Я так понимаю в этом файле должны быть миксины: 'retinaSprite' и 'sprite'
но на деле там только 'retinaBackground', о которой ничего не написано

**Comment by jt3k** [comment]
там какое-то хитрое сочетание вот этих пакетов
https://github.com/reducejs/gulp.spritesmith-multi
https://github.com/CSSSR/spritesmith-dir-checker
https://github.com/CSSSR/spritesmith-stylus-retina-template

не разбирался, но по последней ссылке можно найти упоминание о retinaSprite
