### ISSUE TITLE
Error: task completion callback called too many times

### ISSUE THREAD

**Issue by dmitrylebedev** [CSSSR/csssr-project-template#169]
Привет! Подскажите, с чем может быть связана проблема? 
Я всего лишь скачал проект и написал одну строку в js.
![image](https://cloud.githubusercontent.com/assets/9784329/19575733/cc9143da-9718-11e6-9f53-14347e4d1da6.png)

**Comment by YSXrus** [comment]
Плюсую, такая же беда. Что делал:

1. Создал блок "box"
2. В box.js написал следующее:
`console.log('hello world');`
3. Подключил это чудо в scripts/app.js, который после всех манипуляций выглядит так:
```
import svg4everybody from 'svg4everybody';
import $ from 'jquery';
import '../blocks/box/box.js';

$(() => {
	svg4everybody();
});
```
После сохранения изменений вываливается та же ошибка, что и на скриншоте выше. Пробовал перенести box.js и положить рядом с app.js - результат тот же.
Думал, может быть проблема в том, что babel-register с ошибками устанавливался. Но после их исправления ничего не поменялось.

**Comment by jt3k** [comment]
подтверждаю. 

[нашёл решение](http://stackoverflow.com/questions/32661882/avoid-the-task-completion-callback-called-too-many-times): 
Посоны говорят, что для webpack-watch не нужно вызывать gulb callback();

хотфикс в пути )

**Comment by YSXrus** [comment]
Спасибо, ошибки вроде ушли, хотя с фиксом как-то удалось их снова раз вызвать. Но консоль пуста, Hello World не выводит. Тыкните носом нуба, что я пропустил? )

**Comment by jt3k** [comment]
@YSXrus оно ещё не влито в эту репу.  Или вы из моей репы выливали для тестирований ?

**Comment by YSXrus** [comment]
@jt3k бабушкино-воровским методом посмотрел что было изменено и себе заменил )

**Comment by jt3k** [comment]
@YSXrus   Еси этот фикс не работает, то надо капать дальше.

А есть какая-нить последовательность действий после чего эта же ошибка снова даёт о себе знать ?

**Comment by dmitrylebedev** [comment]
@jt3k, спасибо, у меня работает

**Comment by dmitrylebedev** [comment]
https://github.com/CSSSR/csssr-project-template/issues/169#issuecomment-258925803, @YSXrus, у меня был закомменчен этот коллбэк: https://github.com/jt3k/csssr-project-template/blob/master/tasks/scripts.js#L31

**Comment by YSXrus** [comment]
@jt3k фикс работает, повторно вызвать ошибки не удаётся. Но изменённый js как не цеплялся, так и не цепляется. Пишу уже напрямую в app.js "console.log('hi');" и тишина. Или оно так работать не будет?
з.ы. и gulp пишет "Requiring external module babel-register", загуглил, вроде это норма, но до конца не уверен. С этим может быть как-то связано?

**Comment by jt3k** [comment]
у меня нет идей

**Comment by YSXrus** [comment]
@jt3k всё, разобрался. Заново стянул шаблон, поставил, все работает. Видимо где-то накосячил пока со старым ковырялся. Спасибо за помощь мил человек. )

**Comment by jt3k** [comment]
посоны, еси всо ок то можно закрывать! Всем спасибо!
