### ISSUE TITLE
Подключение файлов в проект в зависимости от использования блоков

### ISSUE THREAD

**Issue by Sergey-lukinPr** [CSSSR/csssr-project-template#170]
Классный шаблон, только существенный недостаток это то, что при создании блока в сборку автоматически подключаются стили этого блока, даже если этот блок не будет использован на странице. У БЭМ есть такая классная штука, что даже если блок создан, но на странице не используется, то css и js не попадает в сборку, как только блок появится на странице, сборщик это понимает и сам подключает нужные для его реализации файлы (опять удаляем блок - удаляются и его css с js). 
Это очень удобно, т.к. не нужно вручную за всем этим следить, особенно если проект большой, или когда включаешься в работу после перерыва.
У Вас не планируется реализация такой системы в проекте?

**Comment by jt3k** [comment]
А если делать такой функционал, то как проверить какой цсс нужен  конкретной странице а какой не нужен ?

Приходит на ум что-то вроде такого:
Таска сборки джейдов ищет все  блоки использующиеся на странице, и передаёт этот список  таске сборки стилей.
Таска сборки стилей  убирает все стили которых нет в списке переданном из таски сборки джейдов.
после сборки цсса высчитываем контрольную сумму цсс-файла, и сохраняем с именем контрольная_сумма.css , после этого это имя должно быть приинклюдено в качестве цсс-файла к нашей html-странице

.........
выходит жутко не оптимально т.к. на условной странице с корзиной, и  на странице эбаут у нас подключаются разные цсски с частично  одинаковым содержанием.
........

Возможно данную задачу можно решить другим способом -- при помощи webpack-чанков.

**Comment by pickmecoach** [comment]
Вообще есть [UnCSS](https://github.com/giakki/uncss) или [галп-версия](https://github.com/ben-eb/gulp-uncss), если, конечно, я правильно понял.
Флоу описан [тут](https://davidwalsh.name/uncss).

>  supports Javascript-injected CSS

**Comment by Sergey-lukinPr** [comment]
@pickmecoach Спасибо большое за ответ, но это совсем не то. UnCSS - это очень сомнительная штука, которая в серьезных проектах не используется, т.к. очищает в большинстве случаев и нужные стили.

**Comment by vasal886** [comment]
Вот есть такой плагин от бемовцев - https://github.com/dab/html2bl . Можно ли его преобразовать под этот шаблон?
