### ISSUE TITLE
yarn vs npm

### ISSUE THREAD

**Issue by Rabinzon** [CSSSR/csssr-project-template#172]
Замерил время установки модулей: 
- yarn `25,6s`  http://joxi.ru/gmvRpO5sx5vNJm
- npm `2:27,12s`  http://joxi.ru/823Od4RT6ZDqe2

О чем тут говорить ?:)  Все кому лень ставить yarn, могут продолжать юзать npm для установки зависимостей.

**Comment by jt3k** [comment]
норм. тока в ридмишку необходимо добавить имхо.
чтото типа "еси стоит yarn то можно yarn install, для остальных людей npm install"
