### ISSUE TITLE
Пустая страница

### ISSUE THREAD

**Issue by Resident234** [CSSSR/csssr-project-template#174]
По адресу http://localhost:3000/ открывается пустая страница https://gyazo.com/52ec0643e57c1eae2ce41dfdd030222a . Так и должно быть ?

**Comment by kuflash** [comment]
@Resident234 если вы склонировали  master ветку, то да. Есть ветка demo, там будет страница с контентом

**Comment by Resident234** [comment]
Спасибо. тему можно закрыть.

**Comment by jt3k** [comment]
@Resident234  для этого нажимай внизу на "Слосе иссуе" ) у нас этой кнопки нет
