### ISSUE TITLE
Gulp падает при пересборке

### ISSUE THREAD

**Issue by Resident234** [CSSSR/csssr-project-template#175]
Вношу, например, изменения в \app\blocks\index\index.styl , проект пытается пересобраться и происходит:

> 0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle csssr-project-template@0.24.0~prestart: csssr-project-template@0.24.0
6 silly lifecycle csssr-project-template@0.24.0~prestart: no script for prestart, continuing
7 info lifecycle csssr-project-template@0.24.0~start: csssr-project-template@0.24.0
8 verbose lifecycle csssr-project-template@0.24.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle csssr-project-template@0.24.0~start: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\csssr\node_modules\.bin;D:\Ruby23-x64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%CommonProgramFiles%\Microsoft Shared\Windows Live;C:\PROGRA~2\Borland\CBUILD~1\Bin;C:\PROGRA~2\Borland\CBUILD~1\Projects\Bpl;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ZipGenius 6\;C:\Program Files (x86)\Common Files\DivX Shared\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Windows Imaging\;C:\Program Files (x86)\Universal Extractor;C:\Program Files (x86)\Universal Extractor\bin;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Rational\common;C:\Program Files\nodejs\;D:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Skype\Phone\;D:\Program Files\nodejs\;D:\Program Files\Git\cmd;D:\Program Files\nodejs\node_modules\;C:\Users\GSU\AppData\Roaming\npm
10 verbose lifecycle csssr-project-template@0.24.0~start: CWD: D:\csssr
11 silly lifecycle csssr-project-template@0.24.0~start: Args: [ '/d /s /c', 'gulp --debug' ]
12 silly lifecycle csssr-project-template@0.24.0~start: Returned: code: 1  signal: null
13 info lifecycle csssr-project-template@0.24.0~start: Failed to exec start script
14 verbose stack Error: csssr-project-template@0.24.0 start: `gulp --debug`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid csssr-project-template@0.24.0
16 verbose cwd D:\csssr
17 error Windows_NT 6.1.7601
18 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v7.0.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error csssr-project-template@0.24.0 start: `gulp --debug`
22 error Exit status 1
23 error Failed at the csssr-project-template@0.24.0 start script 'gulp --debug'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the csssr-project-template package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp --debug
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs csssr-project-template
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls csssr-project-template
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

https://gyazo.com/da0d1ba6939fa8ebe9839de9750d8aca

**Comment by Resident234** [comment]
Происходит проблема именно при редактировании .styl . При изменениях в файлах .jade всё в порядке

**Comment by Rabinzon** [comment]
- ubunut 16.04
- node 6.6
- npm 3.10

проверил, все ок.

**Comment by Resident234** [comment]
npm 3.10.8
node v7.0.0
win 7

**Comment by Nitive** [comment]
Ещё актуально?
