### ISSUE TITLE
Как подключить js библиотеку ?

### ISSUE THREAD

**Issue by Resident234** [CSSSR/csssr-project-template#177]
Мне нужно подключить checked-polyfill.js и выполнить этот код
$(function() {
	$('input:radio, input:checkbox').checkedPolyfill();
});
Как это можно сделать ?
Ложу checked-polyfill.js рядом с app.js в папке /app/scripts/ , а $('input:radio, input:checkbox').checkedPolyfill(); прописываю в app.js ?

**Comment by kuflash** [comment]
@Resident234 
1. Идеальный путь такой:
  - Установить npm пакет нужного скрипта
  - Сделать импорт, там где надо
  - Использовать

2. Если скрипта нет в npm/github:
  - Создать блок с скриптом (нужно чтобы он поддерживал модульную систему)
  - Сделать импорт, там где надо
  - Использовать

Если модульная система в скрипте не поддерживается, то гуглить в сторону того, как это решается вебпаком, и дальше использовать второй вариант

**Comment by Resident234** [comment]
Я положил файл скрипта рядом с app.js, в app.js добавил import './checked-polyfill.js' и сейчас app.js выглядит вот так : 

> 
> import svg4everybody from 'svg4everybody';
> import $ from 'jquery';
> import './checked-polyfill.js';
> 
> $(() => {
> 	svg4everybody();
> });
> 
> $(function() {
> 	$('input:radio, input:checkbox').checkedPolyfill();
> });

Так првильно ?

**Comment by kuflash** [comment]
@Resident234 Правильно, на работать скорее всего не будет.
Еще раз повторяю:
> Если модульная система в скрипте не поддерживается, то гуглить в сторону того, как это решается вебпаком, и дальше использовать второй вариант

**Comment by jt3k** [comment]
Всо ок оно теперь поддерживает  Модульность -- код можно взять например тута 
https://github.com/rdebeasi/checked-polyfill/pull/8
