### ISSUE TITLE
Как считывать json-данные из файла, расположенного в самом блоке?

### ISSUE THREAD

**Issue by vasal886** [CSSSR/csssr-project-template#179]
Можно ли в этом шаблоне считывать данные json с файла, расположенного в блоке, как с папки data?
Если да, то дайте пример пожалуйста.

**Comment by jt3k** [comment]
для этого понадобится "json-loader".
но качать его не придётся.

 я сделал так:
В папке blocks/page создал file.json с содержимым:
```json
{
	"LALALA": "lololo"
}
```
 затем в scripts/app.js добавил это.
```js
import json from '../blocks/page/file.json';
console.log('json', json);
```

после этого шаблон сам слил и приинклюдил json-loader и  на странице я увидел результат:
![2016-11-10 10 53 23](https://cloud.githubusercontent.com/assets/1261240/20168587/0e2f9b86-a734-11e6-9850-85769799a8ac.png)

**Comment by vasal886** [comment]
Спасибо -чето сложновато. Весь Json сливается в js-файл - зачем? А как вытянуть оттуда сведения в Jade-файл?

**Comment by jt3k** [comment]
Чтобы использовать данные из json-файла в jade-шаблонах делай так:

1) создаёшь жсон файл в app/data/
я создал файл file.json
```json
{
	"lala": "LOLO"
}
```

затем в джейд шаблоне делаешь вот так:
```jade
- var json = getData('file');
div.my-block= json.lala
```
или вот так:
```jade
div.my-block= getData('file').lala
```

**Comment by vasal886** [comment]
Да это понятно- это стандартный вывод json из app/data в jade-файл. А я в начале спрашивал как в блоке из созданной папки block/data/file.json вывести json этого блока в миксин этого блока?

**Comment by jt3k** [comment]
@vasal886 загружать жсоны из других  директорий кроме data нельзя.
см. в реализацию данного модуля https://github.com/CSSSR/jade-get-data/blob/master/index.js
там [есть проверка](https://github.com/CSSSR/jade-get-data/blob/master/index.js#L10) на то является ли [результирующий путь](https://github.com/CSSSR/jade-get-data/blob/master/index.js#L8) тем [который был указан при инициализации](https://github.com/CSSSR/jade-get-data/blob/master/index.js#L4)

и если нет то выбрасывает ошибку.

Если сильно надо - скопируй код данной функции напрямик в [templates.js](https://github.com/CSSSR/csssr-project-template/blob/master/tasks/templates.js#L16)  тем самым доработав шаблон под свои нужды ;) luke

**Comment by vasal886** [comment]
Та не особо надо-просто есть модули блоков со своими данными по умолчанию. С функционалом в галп-файле не особо дружен. Вообщем спасибо за отзывчивость!
