### ISSUE TITLE
js блоки

### ISSUE THREAD

**Issue by c1n1k** [CSSSR/csssr-project-template#181]
Как подключать js файлы из папок блоков?

**Comment by Rabinzon** [comment]
@c1n1k импортировать в app/scripts/app.js
`import Block from '../blocks/blockName/fileName';` 
вызвать конструктор, либо инициализирующею функцию:
```
$(() => {
   svg4everybody();
   new Block();
   или
   Block();
});
```
https://github.com/CSSSR/csssr-project-template/blob/master/app/scripts/app.js#L5

**Comment by jt3k** [comment]
@Rabinzon, @c1n1k, не обязательно должен быть конструктор или инициализирующая функция. Из модуля можно вообще любую сущность  экспортировать.

при этом первый вызов  как бы кеширует модуль и  все последующие вызовы будут возвращать тот же самый модуль..

Хорошим решением будет выплёвывать из модуля  объект  с необходимыми свойствами и методами.

также есть вариант  экспортировать адресно функции  или переменные/константы
чтото типа `export const lala = 'lolo';`

**Comment by dmitrylebedev** [comment]
>Хорошим решением будет выплёвывать из модуля объект с необходимыми свойствами и методами.

@jt3k, можете привести пример? Я последнее время думаю, как можно оптимизировать app.js, чтобы писать в нём как можно меньше инициализирующих функций

**Comment by dmitrylebedev** [comment]
@jt3k, и если вы подключаете плагин, вы тоже для него будете создавать объект?

**Comment by jt3k** [comment]
@dmitrylebedev пример:
```js
export default {
  init() {
    /* инициализация какаянить */
  }
}
```
если  подключаем плагин, то из модуля можно ничего  не возвращать..

например если это жквери плагин то внутри  этого плагина должно быть как-то так:

```js
import $ from 'jquery'

$.fn.myPlugin = function () {
  /* ... */
};
```

и тогда подключаем этот плагин  например в модуле plugins.js или в app.js вот так
```jsimport from './my-plugin.js';```
