### ISSUE TITLE
Графика

### ISSUE THREAD

**Issue by dojdev** [CSSSR/csssr-project-template#182]
Как импортировать изображения из папок с блоками в одну папку dist/assets/images?

**Comment by jt3k** [comment]
@dojdev встроенной возможности нет, придётся дорабатывать шаблон.

**Comment by dojdev** [comment]
рабочий вариант
var flatten = require('gulp-flatten');

gulp.task('picsFromBlocks', function() {
gulp.src('blocks/**/*.{png,jpg,jpeg}')
.pipe(flatten({ includeParents: 0} ))
.pipe(gulp.dest('assets/images'));
});

**Comment by jt3k** [comment]
Спасибо за предоставленое решение! Наверняка комунить понадобится

**Comment by mshlmv** [comment]
Куда фоновые изображения складывать для страниц?

**Comment by jt3k** [comment]
@mshlmv  можно в /resources/ 

* а можно например в папку блока где юзаешь этот фон. Но тогда  нужно будет дорабатывать соответствующий лоадер в конфиге вебпака.  Чтобы он сам брал фон и клал куда нужно.

я использую первый вариант и не парюсь. :)
