### ISSUE TITLE
gulp-stylint error

### ISSUE THREAD

**Issue by azimov93** [CSSSR/csssr-project-template#184]
![screen shot 2016-12-01 at 10 02 18 pm](https://cloud.githubusercontent.com/assets/17800754/20810288/e120be10-b811-11e6-8943-93abc2f38601.png)

Посмотрите внимательно на код этого таска!

Импортируете:
`import stylint from 'gulp-stylint';`

А используете как:
`reporter: 'stylint-stylish'`

Из-за этого ошибки:
![screen shot 2016-12-01 at 10 07 58 pm](https://cloud.githubusercontent.com/assets/17800754/20810522/ba56f866-b812-11e6-868b-7781e62a1e6c.png)
![screen shot 2016-12-01 at 10 08 14 pm](https://cloud.githubusercontent.com/assets/17800754/20810528/be121526-b812-11e6-9d05-74ef5c7006ba.png)

**РЕШЕНИЕ ПРОБЛЕМЫ**
В файле 'tasks/styles.js' переписать:
`reporter: 'stylint-stylish'`
на:
`reporter: 'stylint'`

**Comment by kuflash** [comment]
@azimov93 код этого таска верный. `stylint` испортируется и используется [тут](https://github.com/CSSSR/csssr-project-template/blob/master/tasks/styles.js#L38) и еще ниже в 42, 43 строках. `reporter` также здесь задан верно. Вот [тут](https://github.com/danielhusar/gulp-stylint/blob/master/readme.md#reporter) в самом конце документации есть пример использования.

Скорее всего у вас не поставился пакет `stylint-stylish`, NPM бывает грешит этим. Попробуйте его руками поставить и проверить работу таска.

**Comment by jt3k** [comment]
кстати,  я тут заметил, что в [документации](https://github.com/danielhusar/gulp-stylint/blob/master/readme.md#reporter) указан репортер в репортере
![](https://i.imgur.com/cyGYHgG.png)
Может в этом проблема ?

**Comment by azimov93** [comment]
Поставил `stylint-stylish`
![screen shot 2016-12-02 at 9 14 19 am](https://cloud.githubusercontent.com/assets/17800754/20825888/e86fdddc-b86f-11e6-9e38-f4b6d733451d.png)

Вернул `reporter`, но! ошибка осталась:
![screen shot 2016-12-02 at 9 14 48 am](https://cloud.githubusercontent.com/assets/17800754/20825945/428cf778-b870-11e6-9678-94c061b2d162.png)

**Comment by jt3k** [comment]
@azimov93 а пробовал сделать как я описал  в комменте выше ?

**Comment by azimov93** [comment]
@jt3k пробовал. Та же ошибка. Пока только вариант с `reporter: 'stylint'` остается рабочим.

**Comment by kuflash** [comment]
Да, ошибка проявляется. У меня валится [тут](https://github.com/SimenB/stylint/blob/master/src/core/init.js#L30)

Туда попадает не строка а объект:
```js
reporter: {
  reporter: 'stylint-stylish',
  reporterOptions: {verbose: true}
}
```

Пока нет времени разобраться где именно косяк. Попробую вечерком поковырять

**Comment by i-chet** [comment]
У меня такая же проблема!
Пилил, значит, проект, пилил - всё нормально работало. Почти на финале началась эта бадяга:
Error in plugin 'gulp-stylint'
Stylint failed for blocks\about\about.styl
Файл стилей ни в какую не хочет собираться... Подскажите что можно сделать?

**Comment by jt3k** [comment]
@i-chet  если проблема в линтере то просто закомментируй  pipe с стайллинтом и всё
