### ISSUE TITLE
Stylelint warning

### ISSUE THREAD

**Issue by rustamyusupov** [CSSSR/csssr-project-template#185]
Если подключаю спрайт как в ридми:
```
.joy
    sprite $joy
```
то выдает ошибку:
<img width="328" alt="screen shot 2016-12-03 at 6 07 57 pm" src="https://cloud.githubusercontent.com/assets/16702553/20859593/c7d6ec26-b984-11e6-9607-47dcfd6de2ed.png">

Если в скобках:
```
.joy
    sprite ($joy)
```
то все ок.

Что я делаю не так?

**Comment by jt3k** [comment]
да, надо в скобках `sprite($checkmark_blue)` и если в имени есть минусы `-` то нужно их заменить на подчёркивания `_`

**Comment by rustamyusupov** [comment]
С подчеркиванием уже разобрался. Спасибо!
