### ISSUE TITLE
Ошибка при сборке спрайтов

### ISSUE THREAD

**Issue by atomr-web** [CSSSR/csssr-project-template#187]
При использовании спрайтов на выходе в background-image подключается не сам собранный png спрайт, а, почему то, css. Также остаются пустые свойства width, height и bg-position.
`    background-image: url(http://localhost:3012/assets/styles/app.min.css?rel=1481171856019);`
`    background-position: ;`
`width: ;`
`height: ;`

**Comment by Rabinzon** [comment]
@atomr-web сейчас попробовал все сделать по [инструкции](https://github.com/CSSSR/csssr-project-template#Как-собираются-и-используются-png-спрайты), работает. 

создал папки `app` -> `sprites` -> `js`. в js кинул png c размером 128x128.
сборщик сгенерировал файл в `app` -> `styles` -> `sprites` с названием спрайта, у меня `js.styl`. В нем все данные, которые насколько я понял, нам не нужны.  http://joxi.ru/EA4NL13hwwO7Em

далее в любом файле стилей, достаточно добавить `sprite $название_png_файла` или `retinaSprite sprite $название_png_файла`
пример:
```
.node-icon
	sprite $nodejs
```
```
.node-icon {
  background-image: url("../images/sprites/js.png");
  background-position: -136px 0px;
  width: 128px;
  height: 128px;
}
```

**Comment by atomr-web** [comment]
Странно, видимо где то ошибся. Спасибо за ответ
