### ISSUE TITLE
Bemto

### ISSUE THREAD

**Issue by movasyl** [CSSSR/csssr-project-template#189]
Извините, не нашел ответа. В http://cpt.csssr.ru указана библиотека bemto.jade
Используеться ли она еще и как на счет pug-а?

**Comment by jt3k** [comment]
Бемту используется.   -- это миксины +b и +e в jade-файлах.

Насколько мне известно, bemto не совместим с pug  -- там какой-то нелепый екзепшн возникает после того как мы пытаемся  юзить подчёркивания после точки `+b.myblock._mod`

**Comment by movasyl** [comment]
Дело кажется не так в екзепшенах, сколько в разговорах... Перепробовал сегодня кучю вариантов, не вижу проблем. Единственное что нужно - переписать форматы файлов и дописать в інклюды розширения.
Спасибо за ответ.
![default](https://cloud.githubusercontent.com/assets/14804982/21077916/f3232eaa-bf63-11e6-8ec4-cbeb93dbb4ae.PNG)

**Comment by Lehakos** [comment]
Уже выпустили же bemto для pug https://github.com/kizu/bemto

**Comment by jt3k** [comment]
ага на празднiках

**Comment by lamartire** [comment]
Очень странно. Как использовал старый bemto с pug, так и использую. Совершенно никаких исключений не было и все отрабатывает на ура.
Странно, что вообще что-то отломалось. По-сути, jade и pug обратно совместимы, если конечно я не ошибаюсь.
