### ISSUE TITLE
project template и php (yii)

### ISSUE THREAD

**Issue by adminhatep** [CSSSR/csssr-project-template#190]
Доброе время суток!
простите за нубский вопрос...
как можно этот проект прикрутить к php (а именно к yii)
хочу пользоваться всеми плюшками этой сборки как при верстке макетов, так и после разработки (программирования) проекта.
т.е сейчас можно работать со сборкой и генерировать статику и отдавать ее программисту, который будет ее прикручивать к yii, и следовательно когда проект запустится, то все изменения во фронтенде придется делать во вьюхать и тд, чего не хотелось бы.
дайте направление.

**Comment by jt3k** [comment]
Весь проект хранить в отдельной папке в корне сайта.
Пусть бекенд-программист прикручивает  /frontend/dist/index.html при помощи пххпшного include

если нужно прокинуть какие-то переменные из пхп внутрь то  делай пхп-вставки
например  вот так

```jade
        //- /////////////////////////////////////////////
        //- переменная содержит объект с php-вставками (по умолчанию isPROD == true)
        - var php = isPROD ? getData('php') : getData('snipets')

        //- переменные из data/ папки
        - var data = php.data;

        if isPROD
            script.
                var data = !{data};

        else
            // is DEV
            script.
                var data = !{JSON.stringify(data)};
```

здесь переменная isPROD  определяется [вот здесь](https://github.com/CSSSR/csssr-project-template/blob/master/tasks/templates.js#L17) -- можно там написать что-то вроде `isPROD: process.env.NODE_ENV`

Ну и в папку app/data/  положи два файла snipets.json и php.json
внутри  первого будут твои переменные для отладки без пхп-бекенда, а  внутри второго должно быть примерно такое содержание:
```json
{
	"data" : "<?php echo $data; ?>"
}
```

Я не описываю подробно. но если что-то не понятно то спрашивай
