### ISSUE TITLE
babel

### ISSUE THREAD

**Issue by c1n1k** [CSSSR/csssr-project-template#191]
Можно ли как-то убрать код babel из app.js?

**Comment by jt3k** [comment]
что вы имеете в виду ?

**Comment by c1n1k** [comment]
чтобы в app.min.js ничего не попадало кроме того что в app.js

ср, 21 дек. 2016 г. в 23:17, Andrey Gurtovoy <notifications@github.com>:

**Comment by jt3k** [comment]
если из апп-жс всё удалите то  в апп.мин.жс ничего не попадёт (кроме модульной системы  которая от webpack приходит туда)

**Comment by jt3k** [comment]
возможно после production-build всё станет ещё лучше.  (надо смотреть)
