### ISSUE TITLE
Ветки при клонировании

### ISSUE THREAD

**Issue by sagdeev** [CSSSR/csssr-project-template#193]
Привет!
Простите за нубский вопрос, но прошу помочь.
Сделал небольшой проект, SPA на ангуляре, и хочу на гитхаб выложить.
Подскажите, лучше сделать так?

1. Склонировал репозиторий к себе. Теперь в **`master`** сам шаблон, также и в **`remote origin`**.
2. Создать ветку **`dev`**. Здесь собственно разработка приложения.
3. Создать ветку **`prod`**. Уже продакшн версия, её пушить на гитхаб. В **`remote prod`** указать мой репозиторий.

Плюс настроил Travis. После пуша деплой на [Surge.sh](https://surge.sh). Протестил, все работает.

**Comment by jt3k** [comment]
не уверен что полностью понял но норм!
