### ISSUE TITLE
Выпиливается ли при сборке production-build в app.min.js код вебпака?

### ISSUE THREAD

**Issue by vasal886** [CSSSR/csssr-project-template#203]
Объясните нубу в тонкостях галп-сборки почему попадает в продакшин куча ненужного кода из вебпака? Или я ошибаюсь?

**Comment by Nitive** [comment]
Это нужный код, его не куча. Попадает в сборку потому что код собирается вебпаком. Нужен для обеспечения модульности

**Comment by vasal886** [comment]
Обеспечение модульности - всмысле чтобы потом при коректировке проекта все собиралось как при разработке?

**Comment by Nitive** [comment]
https://learn.javascript.ru/modules
