### ISSUE TITLE
Svg спрайт не подгружается на страницу

### ISSUE THREAD

**Issue by MaxVilson** [CSSSR/csssr-project-template#205]
Добрый вечер!
Не могу разобраться как использовать svg спрайт. 
Спрайт лежит в собранном виде в папке assets/images/.
Вызываю его: use(xlink:href='assets/images/icon.svg#icon_twitter'), но на страницу он не подгружается. Помогите пожалуйста разобраться в данной проблеме.

**Comment by jt3k** [comment]
попробуй открыть спрайт по прямой ссылке например localhost:3000/assets/images/icon.svg
тут три варианта:
1)  спрайт будет отсутствовать (404)
2) спрайт найден но  отображаются ошибки XML парсера
3) всё ок и ты видишь белую страницу.

**Comment by MaxVilson** [comment]
Все ок, вижу белую страницу с загруженным спрайтом.

**Comment by MaxVilson** [comment]
Тогда почему не работает вот эта конструкция: use(xlink:href='assets/images/icon.svg#icon_twitter')?

**Comment by kuflash** [comment]
@MaxVilson а посмотри содержимое спрайта при запросе в браузере. Есть ли там твоя иконка?

**Comment by MaxVilson** [comment]
@kuflash Да, в спрайте моя иконка есть: <symbol id="icon_twitter" viewBox="0 0 100 100">
       <path fill-rule="evenodd" fill="rgb(239, 235, 228)" d="....

**Comment by kuflash** [comment]
@MaxVilson именно при запросе из браузера? Просто может быть такое, что локальный сервер чудит с кэшем. А вообще очень странно. Если бы можно было живьем твой пример глянуть, то было бы легче определить проблему. Можешь создать репу?

**Comment by MaxVilson** [comment]
@kuflash Вот тестовый репозиторий: https://maxvilson.github.io/test/
Я немного разобрался, они у меня не отображались по той причине что я задал тегу svg width и height 20px, тогда не понятно как управлять размером иконок? И почему во вкладке "Sources", я не вижу что спрайт загрузился на страницу?

**Comment by kuflash** [comment]
@MaxVilson ну спрайт загрузился у меня http://s.csssr.ru/U04LFCTTB/2017-04-18-1553-9gs0lz0fgp.png

С размерами действительно какая-то лажа. Попробуй открыть свою иконку в каком-то редакторе, и посмотреть какие у нее размеры относительно холста. Возможно холст больше чем сама иконка.

**Comment by MaxVilson** [comment]
ее размеры:
    <width="16px" height="13px">

**Comment by kuflash** [comment]
@MaxVilson а размеры холста больше. Нужно исправить иконку. Исправить viewbox на размеры иконки. Сейчас у тебя там 100x100

**Comment by MaxVilson** [comment]
@А можно ли это сделать автоматически?

**Comment by kuflash** [comment]
@MaxVilson не могу точно сказать. Возможно есть инструменты для этого. 
Но это уже другая история, которая не касается нашего шаблона)

**Comment by MaxVilson** [comment]
@kuflash А когда тогда вы используете svg-спрайты на проектах? Может есть примеры? Или вы вручную меняете viewbox?

**Comment by kuflash** [comment]
@MaxVilson меняем вручную, там где необходимо

**Comment by MaxVilson** [comment]
@kuflash Ясно, спасибо тебе большое за помощь!
