### ISSUE TITLE
Никак не заведется у меня шаблон

### ISSUE THREAD

**Issue by m1roku** [CSSSR/csssr-project-template#209]
Драсти, скачал, nmp install, потом пришлось обновить node.js, потому что шаблон не запускался и просил убедится в том что она у меня самая новая. И все равно остается ошибка после npm start:

user:Organic user$ npm start

> csssr-project-template@0.26.2 start /Users/user/PsdToHtml/Organic
> gulp --debug

[16:34:00] Requiring external module babel-register
/Users/user/PsdToHtml/Organic/tasks/copy.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected token import
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at loader (/Users/user/PsdToHtml/Organic/node_modules/babel-register/lib/node.js:144:5)
at Object.require.extensions.(anonymous function) [as .js] (/Users/user/PsdToHtml/Organic/node_modules/babel-register/lib/node.js:154:7)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! csssr-project-template@0.26.2 start: `gulp --debug`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the csssr-project-template@0.26.2 start script 'gulp --debug'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the csssr-project-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! gulp --debug
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs csssr-project-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls csssr-project-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/user/PsdToHtml/Organic/npm-debug.log

**Comment by m1roku** [comment]
Дополню, спустя пять дней я таки решился использовать windows, поставил node.js v6 и все прошло как по маслу с первого раза. На mac же все без изменений, так и не придумал я почему.

**Comment by jt3k** [comment]
попробуй грохнуть ноду и установить по новой.
у меня к сожелению нет идей :(

**Comment by ledniy** [comment]
была такая проблема когда копировал проект не через git, и забыл все dot файлы (без .babelrc именно такая ошибка)

**Comment by m1roku** [comment]
Ебушки воробушки оно живое, не хочется, конечно, признаваться в такой глупости но это действительно так. Не зацепил дот файлы.
