### ISSUE TITLE
Хелп! - error  '$' is not defined

### ISSUE THREAD

**Issue by dimaskiev** [CSSSR/csssr-project-template#210]
Привет
Уже день бьюсь с такой проблемой error  '$' is not defined

app.js выглядит так
`import svg4everybody from 'svg4everybody';
import $ from 'jquery';
require('../blocks/futures/futures.js');

$(() => {
    svg4everybody();
});`

Хелп!

**Comment by jt3k** [comment]
Внутрт футурес жс нет импорта жыквери?

**Comment by dimaskiev** [comment]
В футуресе нет импорта jquery.
Ошибка есть, но все работает)
Как вариант вижу отключить в eslint показ ошибки not defined (попробовал - линт проходит, все пушится, но понимаю что это не решение, а костыль)

**Comment by jt3k** [comment]
так добавь импорт jquery .  у нас же модули, и доллар  теперь не глобальный

**Comment by dimaskiev** [comment]
Так и сделал в принципе

**Comment by jt3k** [comment]
помогло ?

**Comment by dimaskiev** [comment]
да, все ок
