### ISSUE TITLE
Ошибка со сборкой стилей

### ISSUE THREAD

**Issue by RinatValiullov** [CSSSR/csssr-project-template#211]
После добавления любых стилей в файл *app.styl* возникает ошибка.

![sublime_text_2017-08-22_22-48-28](https://user-images.githubusercontent.com/9755333/29579361-0e2acc4e-878c-11e7-9a72-6b12f9cd295e.png)
Не могу разобраться в чем причина...

**Comment by jt3k** [comment]
подтверждаю проблему на osx sierra ❯ node v8.3.0

**Comment by jt3k** [comment]
@RinatValiullov
1) Проблема пропадает если написать стили перед import('../blocks/**/*')
2) По правилам БЭМ ты **не** должен вешать правила на тэги, а только на классы.
  Правильным решением будет создать блок  page `npm run make-block page`, и добавить класс `page` к `<body>`
  , а в app.styl не писать никаких стилей.
