### ISSUE TITLE
Валится установка

### ISSUE THREAD

**Issue by c1n1k** [CSSSR/csssr-project-template#213]
вот ошибка 
```index.js -> dist\index.js
npm ERR! path D:\Work\Dropbox\work\Project\mbib\markup\node_modules\nan\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\Work\Dropbox\work\Project\mbib\markup\node_modules\nan\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\Work\Dropbox\work\Project\mbib\markup\node_modules\nan\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\Work\\Dropbox\\work\\Project\\mbib\\markup\\node_modules\\nan\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\Work\\Dropbox\\work\\Project\\mbib\\markup\\node_modules\\nan\\package.json' }```

**Comment by jt3k** [comment]
Судя по ошибке, у твоего пользователя в командной оболочке не хватает прав на удаление символьной ссылки. Погугли этот PERM плз21:28, 30 августа 2017 г., Oleg <notifications@github.com>:вот ошибкаnpm ERR! path D:\Work\Dropbox\work\Project\mbib\markup\node_modules\nan\package.jsonnpm ERR! code EPERMnpm ERR! errno -4048npm ERR! syscall unlinknpm ERR! Error: EPERM: operation not permitted, unlink 'D:\Work\Dropbox\work\Project\mbib\markup\node_modules\nan\package.json'npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\Work\Dropbox\work\Project\mbib\markup\node_modules\nan\package.json'npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\Work\\Dropbox\\work\\Project\\mbib\\markup\\node_modules\\nan\\package.json\'',npm ERR!   errno: -4048,npm ERR!   code: 'EPERM',npm ERR!   syscall: 'unlink',npm ERR!   path: 'D:\\Work\\Dropbox\\work\\Project\\mbib\\markup\\node_modules\\nan\\package.json' }```—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.    Написано руками мобильной Яндекс почтой.

**Comment by c1n1k** [comment]
как-то странно, не с того не с сего вдруг права обрубились? я пробовал и с правами администратора запускать и другую оболочку

**Comment by jt3k** [comment]
Попробуй не в папке дропбокса это делать. Дропбокс может химичить с правами удаляя/портя символьные ссылки. А это важно

**Comment by c1n1k** [comment]
от папки там только название, дропбокса уже несколько лет нет

**Comment by jt3k** [comment]
Попробуй снести node_modules и проинсталить заново `npm i` и если не поможет то `yarn`

**Comment by jt3k** [comment]
Посмотри как решили проблему здесь https://github.com/Medium/phantomjs/issues/19

**Comment by c1n1k** [comment]
пробовал кеш чистить, в большинстве это советуют, попробовал отключить антивирус, тоже ничего. попробую yarn

**Comment by c1n1k** [comment]
Только yarn и помог. В чем может быть причина? в fsevents?

**Comment by jt3k** [comment]
мне кстати тоже в последнее время с npm не везёт :( 
```
npm -v && node -v
5.3.0
v8.3.0
```

**Comment by c1n1k** [comment]
сообщение из лога 
```verbose unlock done using C:\Users\user\AppData\Roaming\npm-cache\_locks\staging-aa7b3a9622dcd828.lock for D:\t\tt\node_modules\.staging```

**Comment by jt3k** [comment]
Хз воппщем

**Comment by yunusga** [comment]
Можно попробовать откатиться на `npm 5.2`, 5.3 вышел глюкавым

**Comment by c1n1k** [comment]
На винде можно пользоваться встроенной ubuntu, её можно через магазин уже вроде поставить. Там установка через npm идёт нормально, кроме предупреждений на fsevents.
