### ISSUE TITLE
Как реагировать на это сообщение в консоли?

### ISSUE THREAD

**Issue by Manikhin-KM** [CSSSR/csssr-project-template#214]
styles:lint выдаёт такое сообщение: 'prefer custom grouped when sorting properties', как на него реагировать, как правильно писать свойства?

**Comment by jt3k** [comment]
Глянь в конфиг стилинта.

Также товарищ @nitive может подсказать где взять писанный им плагин для sublimetext,  который помогает полуавтаматически сортировать порядок свойств исходя из того что указанно в stylint-конфиге

**Comment by Manikhin-KM** [comment]
Спасибо большое!
