### ISSUE TITLE
Проблема с подключение модулей

### ISSUE THREAD

**Issue by c1n1k** [CSSSR/csssr-project-template#215]
Не могу понять в чем дело.
Устанавил slick, подключилб инициализировал, в общем всё как всегда делал, но он плагин не срабатывает, в консоле браузера сообщение: `Uncaught TypeError: (0 , _jquery2.default)(...).slick is not a function`, такая же ошибка с другим модулем `https://github.com/Dimox/jQueryFormStyler`. Это в модулях ошибка или где-то ещё?

Ставил всё через yarn
Win10 x64
node -v && npm -v
v8.4.0
5.4.0

**Comment by jt3k** [comment]
![](https://i.imgur.com/SwxtsuK.png)
Я слицк подключал вот так. -- глянул в пэкэдж жэсон этого слицка и затем в исходник.  Попробуй.

Инит здесь только чтоб вынести инициализацию в то место когда будет dom-ready

**Comment by jt3k** [comment]
Ещё он у меня недавно перестал работать после очередной пересборки.  Это исправилось установкой последней версии.

**Comment by c1n1k** [comment]
Слик перестал работать?

**Comment by c1n1k** [comment]
не помогает такой способ

**Comment by jt3k** [comment]
Да, слицк перестал работать...  мне кажется там каким-то образом файлы поменяли и сломали. но в  последней версии всё  хорошо.


попробуй установить зависимости с yarn может в этом проблема

**Comment by c1n1k** [comment]
это как зависимости с yarn?

**Comment by c1n1k** [comment]
проблема решилась обновлением jQuery
