### ISSUE TITLE
Как убрать из title надпись DEBUG -, так же как заменить favicon. 

### ISSUE THREAD

**Issue by denisidorenko** [CSSSR/csssr-project-template#216]
Привет, мучаюсь уже пару часов. Как убрать надпись debug, не могу такое запустить в проекте + как заменить favicon'ку

**Comment by Anton9408** [comment]
Привет, тебе нужно запустить `npm run production` чтобы запустилась продакшенская сборка.
А заменить favicon можно тут https://github.com/CSSSR/csssr-project-template/tree/master/app/resources

**Comment by denisidorenko** [comment]
@Anton9408  Спасибо большое
