### ISSUE TITLE
Где могу найти гайд с использованием?

### ISSUE THREAD

**Issue by denisidorenko** [CSSSR/csssr-project-template#217]
Никак не могу понять логику слияния шаблонов. 
Вот пару вопросов
1) Создаю блок через npm. Как его стоит правильно подключать и где он подключать
2) Новые страницы где подключаются зачем в папке blocks папка page
3) Каждая новая страница должна иметь в page?
4) Создаю к примеру header в нем создаются header.jade , header.styl , header.js Как правильно подключать hader.jade к главной странице и где его подключать

**Comment by jt3k** [comment]
1. В файле `app/pages/index.jade` добавь в верху `include /blocks/new-block` где `new-block` - имя созданного блока.
  Также можно инклюдить блоки внутри других jade-файлов.
  Когда ты приинклюживаешь блок на самом деле ты приинклюживаешь "миксин", это как функция которую ты можешь легко "запустить"  написав `+new-block` в том месте где хочешь использовать.
2. Новые страницы добавляются при помощи добавления jade-файлов внутри `app/pages/`. Лично я просто дублирую файл `app/pages/index.jade`
2.1 `blocks/pages` это блок для класса который вешается на `<body>`. Это сделанно для того чтобы следовать методологии БЭМ. Одного блока page вполне достаточно чтобы использовать его на разных страницах (если надо чтото поменять то делай  модификатор и вешай его на блок).
3. Не понял вопроса.  Посмотри на готовый проект в этом репозетории в ветке demo. https://github.com/CSSSR/csssr-project-template/blob/demo/app/blocks/index/index.jade
4. Как писал в пункте 1. можно подключить например в `app/pages/index.jade`. Важно понимать что ты должен подключать эти миксины в тех местах где собираешься их использовать.
  `styl` файлы подключать не надо, они автоматом подключаются
  `js` в ишьюсах много раз спрашивали и отвечали ..  вот например https://github.com/CSSSR/csssr-project-template/issues/37#issuecomment-133813560. Попробуй также поискать там по слову `скрипты` или `js`
