### ISSUE TITLE
Предусматривает сборка работу с библиотеками?

### ISSUE THREAD

**Issue by denisidorenko** [CSSSR/csssr-project-template#218]
Привет ранее использовал сборку которая предусматривала работу с библиотеками к примеру owl carousel и.т.д тем что компилировала весь код в один js. В данной сборке предусматривается что то наподобие либо же стандарт подключать и использовать? Судя по тому как импорт идет в основной js думаю что есть что то. Кстати где лучше всего , в какой папке ставить библиотеки?:

**Comment by jt3k** [comment]
Есть разные способы поставки библиотек.
Когда тебе нужно подключить:
1) только js в виде файла
1) только js в виде url'а на файл
2) когда тебе нужно подключить css, js, и картинки

Ещё бывают случаи когда нужно подключить какую-то библиотеку только после того как подключен jquery.

--- 
Всё расписывать мне лень . если интересен конкретный кейс то спрашивайте здесь, расспишу. (рано или поздно распишу все кейсы =) )

вот те места где ты можешь класть файлы:
- Всё что кладёшь в `/app/resources` после сборки попадёт в корень.
- `app/scripts` - папка для скриптов

вот те места где  можно подключать файлы:
- `app/blocks/head` -> здесь можно подключать также и стили
- `app/blocks/layout-default` -> массив внутри миксина `scripts` эо место сразу перед закрывающим `</body>`
