### ISSUE TITLE
Вопрос по синтаксису

### ISSUE THREAD

**Issue by Yuricoden** [CSSSR/csssr-project-template#219]
![image](https://user-images.githubusercontent.com/19597527/30783303-507aeb8e-a149-11e7-928c-e763af96a627.png)
Что конкретно добавляет приставка атрибут? я просто вижу она ко всем елементам ставиться. Хотя и без нее в теге ничего вроде как не меняется.  И также интересует пристава '+b' и где то '+e' если я верно понимаю то первое ето блок а второе елемент?

**Comment by roxkisrover** [comment]
Есть теги с обязательными атрибутами, как _src_ для `<img>`, а есть с опциональными, например _title_ для `<p>` (нужно смотреть по контексту). Про них подробно расписано в [MDN](https://developer.mozilla.org/ru/docs/Web/HTML/Attributes).

По поводу приставок, если коротко, то да. Подробнее можно почитать в [документации Bemto](https://github.com/kizu/bemto).

**Comment by jt3k** [comment]
1. `&attributes(attributes)` лишь прокидывает аттрибуты в  это место.
Таким образом ты можешь использовать свой миксин вмести со скобочками внутри которых ты перечислишь необходимые для блока аттрибуты, и после этого они попадут в результирующий html.

Другими словами: можешь использовать свой миксин например вот так:
```jade
+new(align='justify')
```
и на выхоже получишь такое
```html
<p class="new" align="justify">
</p>
```

2. `+b` и `+e` это миксины от Bemto(смотри ссылку от @roxkisrover)
Весьма удобная штука? советую почитать про это!.
Там можно делать такие вещи как
```jade
+b.block1._modificator
  +e.element._el-modificator.__element2._modificator
```
гибко и лаконично

Обрати также внимание на ключевое слово `block`,  с ним ты можешь использовать свой миксин например вот так:
```jade
+new
  +e('span').text lololo
  +e.img(src='http://lorempixel.com/200/200/')
  +e('SPAN').important-text lalala lalala
```

и на выходе получишь:
```html
<p class="new">
  <span class="new__text">lololo</span>
  <img class="new__img" src="http://lorempixel.com/200/200/"/>
  <SPAN class="important-text">lalala lalala</SPAN>
</p>
```
Это гибко и иногда пригоджается!

**Comment by Yuricoden** [comment]
Спасибо!А куда нужно добавлять картинки и фоны? Сейчас добавляю в папку resources.

**Comment by jt3k** [comment]
@Yuricoden правильно, туда можно.  создай там папку img  )

**Comment by Yuricoden** [comment]
@jt3k а есть плагин для сортировки stylus кода по BEM?  Использую webstorm ide. Пробовал искать но не нашел.

**Comment by jt3k** [comment]
@Yuricoden товарищ @Nitive сделал [плагин для Sublimetext](https://github.com/Nitive/sublime-stylint-sorting) -- оно сортирует свойства в соответствии c настройке `sortOrder` внутри файла `.stylintrc` наверняка и для вебсторм тоже есть подобный плагин.

Есть ещё csscomb и он может сортировать на лету, но к сожелению csscomb не умеет в stylus.

Вообще можно отключить - просто удали `.stylintrc` ) я всегда так и делаю

**Comment by Yuricoden** [comment]
@jt3k удалил но все равно такая вот ошибка 
![image](https://user-images.githubusercontent.com/19597527/30926408-b46b0bd0-a3bd-11e7-86a1-fdd577828957.png)

**Comment by jt3k** [comment]
Может проблема в вебсторме -- он иногда странным образом работает с файлами. Попробуй 
- проверить удалён ли файл на самом деле
- запустить сборку не в вебсторме

Если не поможет просто найди и отключи таску с линтингом стайлуса (в папке tasks)

**Comment by Yurajun** [comment]
Из поста выше видно что при добавлении блоку через точку класса мы получаем строку
<code>
class="button button_ok"
</code>
Но если в миксин передать какой нибудь параметре то на выходе мы не получим 2 класса
Ниже пример того что при таком синтаксисе я не могу получить 2 класса как написано выше
<code>
include ../button/button

+button('confirm')._ok
	| Добавить

mixin button(action)
	+b.button&attributes({'data-remodal-action': action})
		block
</code>
На выходе 
<code>
class="button"
</code>
Хотел узнать, есть ли вариант решения или просто передавать класс в сам миксин, как параметр?

**Comment by Yurajun** [comment]
Извиняюсь. Нашел решение
```
mixin button(action)
	+b.button(data-remodal-action=action)&attributes(attributes)
		block
```
Все на выходе теперь 2 класса
`class="button button_ok"`

**Comment by jt3k** [comment]
%) кажется ты не правильно используешь шаблон.

Потому что нет смысла в том чтобы определять миксин `mixin button(action)` и тут же  его использовать `+button('confirm')._ok`.  Хотя возможно это так  для примера написано, а на самом деле это 2 разных файла ).

Если тебе необходимо чтобы у каждой кнопки был аттрибут `data-remodal-action="action"` то впринцыпе можно и так. Но я предчувствую что скоро вам понадобятся кнопки без этого аттрибута и нужно будет чтото придумывать ):
