### ISSUE TITLE
Как вывести имя проекта в лэйауте?

### ISSUE THREAD

**Issue by checkonetwo** [CSSSR/csssr-project-template#220]
Подскажите пожалуйста как вывести в переменную имя корневой директории проекта?
У меня много проектов. И в каждом проекте мне нужно генерировать через миксин ссылку с именем директории в которой лежат файлы

%directoryName&/app

Вообщем нужно получить %directoryName&

**Comment by jt3k** [comment]
Смотри в tasks/template
Там есть **обьект** у которого ещё есть метод `getData`.
Тебе надо узнать как в ноде-жс получить имя родительской директории,  вычислить и добавить свойство к этому **объекту**.
А затем в джейд файлах просто пишешь `div= имясвойства` и у тебя будет имя проекта) 👌
