### ISSUE TITLE
SVG спрайт

### ISSUE THREAD

**Issue by pashkes** [CSSSR/csssr-project-template#224]
Как пользоваться svg спрайтом? Перепробовал разные варианты, спрайт загружается, а сама иконка нет
И еще в гайде написано что при вводе команды npm run make-block [имя-блока] создаются файлы стиля,  разметки и скрипта для этого блока, но файл скрипта не создается

**Comment by jt3k** [comment]
1) смени ветку на `demo` и посмотри как там  svg-спрайт делают

2) да, файл скрипта не создаётся ))  скрипты лучше класть в scripts рядом с app.js. чтобы удобно было их оттуда импортировать в app.js

**Comment by pashkes** [comment]
С иконками разобрался, спасибо
