### ISSUE TITLE
Error rupture.styl

### ISSUE THREAD

**Issue by FahrenheitIndi** [CSSSR/csssr-project-template#228]
Добрый времени суток, при запуске команды npm start в консоли ошибка
`app.styl:9:25
    5| @import 'helpers/fonts'
    6| @import 'helpers/optimize'
    7| @import 'helpers/typography'
    8|
    9| import('../blocks/**/*')
------------------------------^
   10|

failed to locate @import file rupture.styl`

Соответственно все media query с использованием rupture не работают.

**Comment by jt3k** [comment]
чтото не то внутри `helpers/typography`

что там ?

**Comment by FahrenheitIndi** [comment]
Разобрались, просто удалили и заново поставили rupture. Ошибка исчезла.
