### ISSUE TITLE
retinaBackground 

### ISSUE THREAD

**Issue by Yurajun** [CSSSR/csssr-project-template#231]
Возможна ошибка в работе "retinaBackground"
Если написать так 
```
.wrapper-index

		min-height 100vh

		&__gradient
			width 100%
			min-height 100vh
			retinaBackground(index-fone-mob, jpg)
```
То на выходе мы получим

```
@media only screen and (max-width: 959px) and (-webkit-min-device-pixel-ratio: 2), only screen and (max-width: 959px) and (min-resolution: 192dpi) {
  __gradient {
    background-image: url("../images/index-fone-mob@2x.jpg");
  }
}
```

где видим интересное название селектора
Если мы напишем 

```
.wrapper-index__gradient

		retinaBackground(index-fone-mob, jpg)
```

то все отработает хорошо

```
@media only screen and (max-width: 959px) and (-webkit-min-device-pixel-ratio: 2), only screen and (max-width: 959px) and (min-resolution: 192dpi) {
  .wrapper-index__gradient {

    background-image: url("../images/index-fone-mob@2x.jpg");
  }
}
```

**Comment by dzhiriki** [comment]
А можно ссылку на репозиторий, где это можно воспроизвести?

Попробовал добавить код из первого фрагмента в пустой шаблон, на выходе получил полный селектор.

**Comment by Yurajun** [comment]
Я просто вставлю полный код styl файла. Скопируйте его к себе и вы увидите ошибку
<code>
.wrapper
	min-height 100vh
	&__bg
		width 100%
		retinaBackground('page', png)


@media only screen and (max-width: 959px)
	.wrapper-index
		min-height 100vh

		&__gradient
			width 100%
			min-height 100vh
			background-repeat no-repeat
			background-position center center
			background-size cover
			retinaBackground(index-fone-mob, jpg)

	.wrapper-index__gradient
		retinaBackground(index-fone-mob, jpg)
</code>

то что в файле css
<code>
.wrapper {
  min-height: 100vh;
}
.wrapper__bg {
  width: 100%;
  background-image: url("../images/page.png");
}
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .wrapper__bg {
    background-image: url("../images/page@2x.png");
  }
}
@media only screen and (max-width: 959px) {
  .wrapper-index {
    min-height: 100vh;
  }
  .wrapper-index__gradient {
    width: 100%;
    min-height: 100vh;
    background-repeat: no-repeat;
    background-position: center center;
    background-size: cover;
    background-image: url("../images/index-fone-mob.jpg");
  }
  .wrapper-index__gradient {
    background-image: url("../images/index-fone-mob.jpg");
  }
}
@media only screen and (max-width: 959px) and (-webkit-min-device-pixel-ratio: 2), only screen and (max-width: 959px) and (min-resolution: 192dpi) {
  __gradient {
    background-image: url("../images/index-fone-mob@2x.jpg");
  }
}
@media only screen and (max-width: 959px) and (-webkit-min-device-pixel-ratio: 2), only screen and (max-width: 959px) and (min-resolution: 192dpi) {
  .wrapper-index__gradient {
    background-image: url("../images/index-fone-mob@2x.jpg");
  }
}
</code>

**Comment by Yurajun** [comment]
Если вставить retinaBackground после media запроса в &__gradient то возникает ошибка. Если в &__gradient будет больше свойств то сборщик скажет вынести retinaBackground отдельным свойством.

**Comment by dzhiriki** [comment]
Это не связано с retinaBackground. Это связано с тем, как Stylus обрабатывает вложенные @media (т.е. с багом в этой обработке).
Если использовать простые @media так же, как и происходит при использовании retinaBackground, то получим точно такой же результат:
```
@media (max-width: 10px)
  .block
    display: block
    &__element
      @media (max-height: 10px)
        display: block
```
=> 
```
@media (max-width: 10px) {
  .block {
    display: block;
  }
}
@media (max-width: 10px) and (max-height: 10px) {
  __element {
    display: block;
  }
}
```
[Try Stylus](http://stylus-lang.com/try.html#?code=retinaBackground(%24image%2C%20%24ext%20%3D%20'png')%20%7B%0A%09background-image%20url('..%2Fimages%2F'%20%2B%20%24image%20%2B%20'.'%20%2B%20%24ext)%0A%0A%09%40media%20(-webkit-min-device-pixel-ratio%3A%202)%2C%20(min-resolution%3A%20192dpi)%20%7B%0A%09%09background-image%20url('..%2Fimages%2F'%20%2B%20%24image%20%2B%20'%402x.'%20%2B%20%24ext)%0A%09%7D%0A%7D%0A%0A%40media%20(max-width%3A%2010px)%0A%20%20.block%0A%20%20%20%20display%3A%20block%0A%20%20%20%20%26__element%0A%20%20%20%20%20%20%40media%20(max-height%3A%2010px)%0A%20%20%20%20%20%20%20%20display%3A%20block)


Как и сказал уже выше, это баг в самом Stylus. [Ссылка на баг](https://github.com/stylus/stylus/issues/1884) там же есть и workaround для подобных случаев.
