### ISSUE TITLE
Сброс шаблона

### ISSUE THREAD

**Issue by dzhiriki** [CSSSR/csssr-project-template#26]
Добавить команду, по которой будет происходить удаление файлов примера

**Comment by jt3k** [comment]
:+1: +1 Напиши плз рекомендации как удалять пример, и я запуллреквестю эту фитчу.
а то мне каждый раз при старте нового проекта требуется пол дня чтоб вкурить как удалить чтоб не поломалось..

**Comment by felixexter** [comment]
Сбрасывать не придётся. Решили, что шаблон будет сразу чистым. Демка будет в отдельной ветке.

**Comment by jt3k** [comment]
Эээ а решение ишьюса не будет?

**Comment by dzhiriki** [comment]
Так выпилили демку из мастера. Теперь демка в отдельной ветке.
