### ISSUE TITLE
Генерация блоков

### ISSUE THREAD

**Issue by dzhiriki** [CSSSR/csssr-project-template#27]
Добавить команду, по которой будет создаваться блок с шаблонным содержимым.
Типа файлов (jade, styl, js) сделать опциональными (ибо не все блоки требуют все файлы).

**Comment by Menma27** [comment]
Мне примерно тоже самое пришло в голову, когда начал работать с этим проектом. Но я это так представил - просто создаёшь папку в block, а там уже все три файла с такими же названиями генерируются. Удалить всегда успеется, если надо.
