### ISSUE TITLE
Крик о помощи.

### ISSUE THREAD

**Issue by dooragon** [CSSSR/csssr-project-template#36]
Доброго времени суток! Очень хочется пройти тестовый квест на должность верстальщика.
Репозиторий не клонировался с заданым адресом(получилось клонировать, задав адрес https://www.github.com/CSSSR/csssr-project-template.git).
Далее установил gulp (глобально), установил npm, задал зависимости,  
Проблема  следующая : 
когда запускаю gulp ничего не происходит(может так и надо),но
перейти на localhost:3000 не выходит.

**Comment by dzhiriki** [comment]
Привет.
1. Чтобы было доступно клонирование по SSH ссылке, должны быть прописаны SSH-ключи. [Подробнее](https://help.github.com/articles/generating-ssh-keys/). Сам шаблон тут не при чем.
2. В консоли выводится порт, на котором открылся шаблон. Сейчас порт по-умолчанию 3001, ридми немного устарело.

**Comment by dooragon** [comment]
Очень спасибо, теперь понятно, буду верстать.

**Comment by felixexter** [comment]
>  Сейчас порт по-умолчанию 3001, ридми немного устарело.
Поправлю. Вернули на 3000, т.к. люди привыкли уже.

**Comment by dooragon** [comment]
SSH-ключи установил, шаблон клонировался по SSH-ссылке,но в gulp'e та же ситуация, на localhost:3000(1) тоже не получается зайти. Может быть такое, что я раньше понаставил всякого(устанавливал npm,gulp в разных папках, gulp сначала ошибку при запуске выдавал (про babel'и что-то ), потом молча стал выполняться) в терминале и из-за этого не работает?

**Comment by dzhiriki** [comment]
Покажи что именно выводится в терминале при запуске gulp'а

**Comment by dooragon** [comment]
ничего не выводится, новая командная строка

**Comment by dzhiriki** [comment]
И никакой ошибки?

**Comment by dooragon** [comment]
~/new-project$ gulp
~/new-project$ dir
app  gulp  gulpfile.js	package.json  readme.md
~/new-project$

**Comment by dooragon** [comment]
может попробовать переустановить node,npm и gulp?

**Comment by dzhiriki** [comment]
Можешь попробовать.
Другие шаблоны с gulp'ом не пробовал запускать? Если и они не запустятся, то дело точно не в шаблоне.

**Comment by dooragon** [comment]
пробовал

**Comment by dzhiriki** [comment]
И какой результат?

**Comment by dooragon** [comment]
такой же, новая командная строка
пробовал этот проект:
http://habrahabr.ru/post/208890/

**Comment by dzhiriki** [comment]
Собственно, тогда дело явно не в шаблоне. Тут уже вряд ли чем мы сможем помочь.

**Comment by dooragon** [comment]
понятно, переустановлю тогда, попробую снова запустить.
