### ISSUE TITLE
Великолепный шаблон, но как пользоваться JS?

### ISSUE THREAD

**Issue by dontlemmedown** [CSSSR/csssr-project-template#37]
Как пользоваться JS? =) 
Т.е, есть 2 блока (допустим):

- widget/
 - /widget.jade
 - /widget.styl
 - /widget.js

#### widget.js
```javascript
class Widget {
	
	constructor(title, content) {
		// TODO
	} 

	init() {
		// TODO
	}
}
```

- someblock/
 - /someblock.jade
 - /someblock.styl
 - /someblock.js

#### someblock.js
```javascript
let myWidget = new Widget('Someblock', 'Lorem ipsum dolor sit amet');
myWidget.init();
```

Соответственно при компиляции: (взял чистый шаблон и добавил виджет, а подключил его в index)
https://github.com/dontlemmedown/anketa/commit/532c517633fd6d4b384a79679a5a489b362dbbae

```console
d:\Projects\anketa\app\blocks\index\index.js
  3:20  error    "Widget" is not defined                           no-undef

d:\Projects\anketa\app\blocks\widget\widget.js
   1:7  error    Widget is defined but never used                  no-unused-var
```

**Comment by dzhiriki** [comment]
Модули.
В widget.js вам нужно ваш класс экспортировать, в index.js импортировать.
+ собираются скрипты из app/scripts/app.js, поэтому импортировать index.js нужно и туда.

**Comment by felixexter** [comment]
#### widget.js
```js
export default class Widget {
// ...
}
```

#### someblock.js
```js
import Widget from '../widget';
```

**Comment by dontlemmedown** [comment]
Спасибо, теперь все стало на свои места=)
https://github.com/dontlemmedown/anketa/commit/f995ba7ae13854b34bb87dffa96889d87110514b
