### ISSUE TITLE
Wrapper's и bem

### ISSUE THREAD

**Issue by dontlemmedown** [CSSSR/csssr-project-template#38]
Допустим есть блок button
```stylus
.button
	padding 15px
	background #9f9
```

И есть нескольк блоков, в которых подключается блок button. Но в каждом из этих блоков, блок button размещается по разному (в одном, float left, в другом относительно блока с position absolute) не суть.

Дак вот, как решать этот вопрос?

Первое, что приходит на ум, это внутри блока(в котором будет размещена кнопка) добавить некий wrapper, который будет управлять **только** расположением кнопки относительно данного блока. т.е

#### someblock.jade
```jade
mixin someblock()
	.someblock

		.someblock-button-wrapper
			+button()
```
#### someblock.styl
```stylus
.someblock-button-wrapper
	position absolute
	top 50%
	left 50%
	transform translate(-50%, -50%)
```

Выглядит хорошо, логично, но не с точки зрения BEM.

с точки зрения BEM, .someblock-button-wrapper - это другой блок, который должен находится  отдельном файле (если я правильно понял код ниже)

https://github.com/CSSSR/sputnik/blob/master/Stylus.md
```stylus
// Хорошо
// project.styl
.project
    // ...

    &__name
        // ...

    &__before
        // ...

// project-container.styl
.project-container
    // ...
```
Но проблема в том, что .someblock-button-wrapper имеет непосредственное отношение к .someblock, и нигде в другом месте использоваться не может. При всем при этом - это блок.

Исходя из этого, есть лишь один выход - сделать этот враппер элементом блока .someblock.

Но тогда "из докладов BEM":
> Блок не может находится в элементе, как и элемент не может иметь своего элемента. Если возникает необходимость в этом, то может быть - это блок?

> - цитата не точная, но звучала как то так..

Так вот, вопрос, как вы решаете это?

**Comment by dzhiriki** [comment]
Все верно, сам button не должен задавать свою расположение.
.someblock-button-wrapper — это должен быть не блок, а именно элемент. 
Цитата видимо очень неточная и там имелось в виду совсем другое. Элементы как раз и используются для задавания расположения элемента.

**Comment by dontlemmedown** [comment]
Я думал - это предназначение модификаторов, но не суть, спасибо за реактивный ответ на вопрос =)

p.s вникаю в ваш шаблон и он не перестает меня удивлять и обучать=) . спасибо за него)

**Comment by dzhiriki** [comment]
Не совсем.
Блок — задает только внутреннее состояние. У него не должно быть, например, и маргинов. Причина в том, что блок должен рендерится правильно туда, куда его и поставили. Если блок будет задавать позиционирование, будет куча проблем.
Соответсвенно, модификаторы блоков задает _внутреннее_ состояние этого блока. Например, кегль больше.
Отступы и позиционирование задается как раз элементами.
Пример:
```
.block
  .block__element //тут отступы, флоаты, позиционирование
    +button()
```
Как результат такой организации: кнопку можно положить в любой элемент, вместо кнопки в элемент можно положить другой блок.
Если бы модификаторы кнопки задавали отступы, то это было бы слишком много ненужных модификаторов (под каждое позиционирование), а если кнопку нужно заменить на другой компонент, то новому компоненту придется прописывать стили с позиционированием от этой кнопки.

**Comment by dontlemmedown** [comment]
Это ясно, я просто думал, что должен быть "некий блок", который по сути не является блоком, а лишь оберткой для другого блока. Но, теперь я понял, что эту задачу выполняет элемент, спасибо.
