### ISSUE TITLE
В css записываются стили с ошибками

### ISSUE THREAD

**Issue by ArtNekki** [CSSSR/csssr-project-template#42]
Здравствуйте, Меня зовут Антон! 

Я решил воспользоваться вашим шаблоном, но когда добавляю или создаю свойства для элементов в файле с расширением .styl…например, 

.grid
	border 1px solid red

	&__row
		display inline-block

возникает ошибка:

/opt/local/www/own/new-project/app/blocks/header/header.styl:11:1
   7| 	&__row
   8| 	  	display inline-block

expected "indent", got “outdent"

---------------------------------------------------------------------------------------------

в итоге в css файл попадает свойство в таком виде “__row”, а должно быть “grid__row”.

Подскажите в чем может быть проблема?

**Comment by frendly** [comment]
Судя по ошибке, ты забыл сделать отступ.
Должно быть что-то подобное:
```
.grid
border 1px solid red
	&__row
		display inline-block
```

**Comment by dzhiriki** [comment]
@ArtNekki Проблема решилась? Совет выше верный. Или требуется еще какая-то помощь? 
Если проблема еще есть, то залей куда-нибудь нерабочий вариант.
p.s. Хорошим тоном считается форкать репу, а не делать свою копию без истории.
