### ISSUE TITLE
Сохранение поддиректорий при сборке Jade

### ISSUE THREAD

**Issue by frendly** [CSSSR/csssr-project-template#44]
Добрый день.
Есть статичный проект с русской и английской версией.
Русская версия лежит в `pages/pagename.jade`
Английская версия лежит в `pages/en/pagename.jade`

По умолчанию gulp складывает все файлы из подпапок в dist.
Как научить gulp правильно обрабатывать поддиректории и сохранить иерархию файлов?

Я переписал такси, указав папку прямо в коде: https://github.com/frendly/TMK2014/blob/master/gulp/tasks/jade.coffee

Это работает, но при сохранении изменений в файле и запуске gulp watch обрабатываются все файлы, а не только измененные.
https://github.com/frendly/TMK2014/blob/master/gulp/tasks/default.coffee
Как это поправить?

**Comment by dzhiriki** [comment]
Добрый день.

В таске templates есть пайп rename, который любую папку в пути файла превращает в `.` https://github.com/CSSSR/csssr-project-template/blob/master/gulp/tasks/templates.js#L35

В вашем случае, нужно лишь убирать префикс `page`. Например:
```
.pipe(rename((path) => {
	path.dirname = path.dirname.replace(/^pages/, '.');
	return path;
}))
```

**Comment by frendly** [comment]
Спасибо, помогло.

На coffescript выглядит так:
```javascript
.pipe rename (path) ->
	path.dirname = path.dirname.replace(/^pages/, '.')
	return path
```
