### ISSUE TITLE
Проблема с "кастомизацией")

### ISSUE THREAD

**Issue by vislogurov** [CSSSR/csssr-project-template#45]
Приветствую. Скачал шаблон, установил зависимости. Перехожу в папку blocks, удаляю ваши блоки и создаю свои. На этом все. Новые файлы подхватываются галпом, но не запускается browser-sync и даже при ручном обновлении страницы изменений не происходит. Извиняюсь за тривиалный вопрос, но как мне свой проект на месте вашего развернуть?

**Comment by dzhiriki** [comment]
Какие-то ошибки при запуске есть?

**Comment by vislogurov** [comment]
http://take.ms/RWWbH

**Comment by vislogurov** [comment]
удалил все из папки blocks и создал свой

**Comment by dzhiriki** [comment]
Так у вас в джейде в страницах стоит импорт блока index. Этого блока нет — вот импорт и не работает.
И в стилях аналогично: попытки импортировать стили блоков, а стилей нет.

**Comment by vislogurov** [comment]
да, те ошибки из консоли ушли. Более того была ошибка в index.jade который в pages лежит, неправильно путь к blocks указал. Но browser-sync по-прежнему не запускается, хотя в консоле reloading browsers вы водит.

**Comment by dzhiriki** [comment]
А что значит «не запускается»? На localhost:3000 ничего не показывается?

**Comment by vislogurov** [comment]
Страница не перезагружается. Не всплывает сообщение Connecting to Browser-Sync

**Comment by gearmobile** [comment]
извиняюсь, что вмешиваюсь в ваш разговор. а ваш шаблон можно использовать безвозмездно? и даже попросить помощи в его изучении? )

**Comment by dzhiriki** [comment]
@vislogurov Т.е. сам сервер работает, контент отдается, не работает лишь перезагрузка страницы?

**Comment by dzhiriki** [comment]
@gearmobile Да, можно. Главное, указывайте авторство и не выдавайте шаблон за свой. 
Помощь — ишью для этого и есть. Спрашивайте что непонятно и пишите если что-то не работает.

**Comment by vislogurov** [comment]
Да, не работает перезагрузка. Хотя я изменял только лишь blocks.

**Comment by dzhiriki** [comment]
@vislogurov А вы используете последнюю версию шаблона? До недавнего времени была проблема с пересборкой новых файлов. Недавно это поправили.
Если последнюю, залейте куда-нибудь нерабочий пример. Посмотрим.

**Comment by vislogurov** [comment]
Использую последнюю версию. https://github.com/vislogurov/template-issue

**Comment by dzhiriki** [comment]
Развернул проект, запустил сервер, меняю содержимое header.jade, страница пересобирается и обновляется.

**Comment by vislogurov** [comment]
перезапустил на localhost:9000 . все отлично заработало. ума не приложу(

**Comment by vislogurov** [comment]
Возникнут ли проблемы ,если Stylus в шаблоне заменить на Sass? Достаточно ли установить gulp-sass и поменять styl на scss  в тасках галпа?

**Comment by chupokamber** [comment]
@vislogurov Тестовое задание нужно для того, чтобы проверить ваши профессиональные качества. В том числе и способность самостоятельно справляться с трудностями. Тестовое задание должно соответствовать заявленным в его описании требованиям.

**Comment by vislogurov** [comment]
Сейчас я не использую Ваш макет для верстки тестового задания. И вопрос о Sass мне кажется вполне закономерным. Наверняка есть готовое решение для этого способа. Спросил,чтобы не заниматься строительством велосипеда)

**Comment by dzhiriki** [comment]
Собственно, если везде поменять stylus на sass, то проблем не возникнет.
