### ISSUE TITLE
Глобальный reset в файле optimize.styl

### ISSUE THREAD

**Issue by gearmobile** [CSSSR/csssr-project-template#46]
Насколько я правильно понимаю, файл `optimize.styl` (`app/styles/base/optimize.styl`) фактически состоит из **двух частей** - глобального `reset` через селектор `*` и `normalize.css`.

Подскажите, (*может я неправильно что понимаю или ошибаюсь*) но:

- применение глобального `reset` через селектор `*` мне кажется несколько *грубоватым решением*;
- сочетание глобального `reset` (общий сброс всего и вся) с `normalize.css` (нормализация) как-то не вяжется (*как мне кажется*); что нормализовать, если все уже было сброшено ранее?

**Comment by dzhiriki** [comment]
Привет.

Не совсем так. Тут скорее ресет + частичный normalize.
У normalize, фактически, тоже две части: первая это унификация отступом \ размеров элементов (например, отступы у заголовков), а вторая решение различных кроссбраузерных проблем (например, display у элементов из HTML5 в ИЕ8-9).
В нашем случае, первая часть normalize заменена на reset. Почему? Просто (нам) так удобнее. Чтобы меньше зависеть от «базовых» стилей некоторых тегов.
Почему `*`? Опять же, удобства ради. Можно перечислить только нужные теги, но это более морочно, а разницы, по сути, никакой.
Если кому-то удобнее чистый normalize.css или чистый reset.css – заменить в проекте его не составляет проблем.

**Comment by gearmobile** [comment]
ок - все понятно. спасибо!
