### ISSUE TITLE
Автозапуск в браузере

### ISSUE THREAD

**Issue by gearmobile** [CSSSR/csssr-project-template#48]
**Доброго времени суток!**

Может я что-то *не заметил или упустил* в шаблоне `csssr-project-template`, но:

- почему **отсутствует автозапуск браузера** по локальному адресу `http://localhost:3000/` при старте шаблона `csssr-project-template`?

Мне кажется не то что неудобным, а просто элементарной тратой времени - вручную вводить `http://localhost:3000/` в адресную строку браузера, чтобы запустить просмотр редактируемой страницы.

**Comment by gitnovikov** [comment]
Доброе! 
На главной странице написано...
Открыть ссылку в браузере по умолчанию:
gulp --open

**Comment by gearmobile** [comment]
пардон - мое упущение! вопрос закрыт. спасибо! )
