### ISSUE TITLE
Как добавлять сторонние js-плагины?

### ISSUE THREAD

**Issue by gearmobile** [CSSSR/csssr-project-template#49]
**Доброго времени суток!**

 - как и куда **добавлять сторонние js-плагины** (к примеру - http://www.idangero.us/swiper/ или jQuery.equalHeights) в шаблон `csssr-project-template`?

- куда делся `bower` - вы убрали его поддержку? Если да - то почему?

**Comment by frendly** [comment]
jquery и svg4everybody сейчас лежат в `package.json`
https://github.com/CSSSR/csssr-project-template/blob/master/package.json#L73

Ваша первая ссылка отдает ошибку `500`

`jQuery.equalHeights` есть среди пакетов:
https://www.npmjs.com/package/jquery-equalheights

**Comment by felixexter** [comment]
От Bower отказались в пользу [NPM](https://www.npmjs.com/). Зачем несколько пакетных менеджеров, если с этим хорошо справляется один.
Добавлять так же, как и в Bower - `npm i -D <название модуля или ссылка>`.
В самом js уже импортировать по аналогии с jquery и svg4everybody.

**Comment by gearmobile** [comment]
Правильно ли я понял **шаги по установке и использованию** сторонних js-плагинов:

1. `npm install --save-dev super-puper-plugin`;
2. в `app.js` добавить строку `import puper from 'super-puper-plugin';`
3. в дальнейшем использовать в `app.js` плагин `super-puper-plugin` по его псевдониму `puper` по назначению.

**Вопрос по контексту** - в файле `app.js` я могу писать код в "чистом" javascript-синтаксисе? Не coffee-script, как изначально у вас создано?

**Comment by dzhiriki** [comment]
Это не CoffeeScript. Это ES2015.

**Comment by gearmobile** [comment]
ок. понятно. спасибо!
