### ISSUE TITLE
Jeet.gs (Lost Grid) и Nib в CSSSR-Project-Template

### ISSUE THREAD

**Issue by gearmobile** [CSSSR/csssr-project-template#50]
**Доброго времени суток!**

В шаблоне `csssr-project-template` отсутствуют пакеты [Jeet.gs](http://jeet.gs/) (или [Lost Grid](https://www.npmjs.com/package/lost-grid)) и [Nib](https://github.com/tj/nib). Почему?

Мне эти пакеты (особенно `Jeet.gs` или `Lost Grid`) кажутся весьма и весьма удобными.

**Comment by dzhiriki** [comment]
Ничего не мешает подключить их у себя или в тех проектах, где это нужно. Шаблон не может содержать всё-всё, что кажется удобным.
Nib у нас не прижился, сетки подходят не подо все проекты.

**Comment by gearmobile** [comment]
Понятно. Спасибо.
