### ISSUE TITLE
csssr-project-template => webpack

### ISSUE THREAD

**Issue by gearmobile** [CSSSR/csssr-project-template#51]
Начал изучать webpack от Ильи Кантора. И такой вопрос возник - у CSSSR были мысли перевести свой csssr-project-template с gulp.js на webpack?

**Comment by felixexter** [comment]
Да такие планы есть. Переписывать не будем, под него будет отдельный репозиторий.

**Comment by dzhiriki** [comment]
Вообще, если задуматься, вебпак – ну совсем не замена галпу. Галп — таскраннер, вебпак — бандлер модулей.
Галп и вебпак вполне использовать вместе. А вебпак можно рассматривать как замену браузерифаю. 
Например, вебпаком нельзя собрать статичный сайт. Ну, наверное, как-нибудь можно, но у меня не получалось. Да и не нужен он для этого.
Так что CPT на вебпаке не будет. Отдельный шаблон для SPA – да, скорее всего будет. Если точнее, у нас уже есть наработки шаблона на вебпаке с реактом, но публиковать его пока что рано.

**Comment by gearmobile** [comment]
понятно. спасибо.
