### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by Lehakos** [CSSSR/csssr-project-template#55]
Здравствуйте. При подключении плагинов jquery через import, всегда в консоли выдает такую ошибку: jquery is not defined. Пробовал сделать import в переменную jQuery, не помогает. Нашел решение только через global.jQuery = require('jquery'). Подскажите, пожалуйста, как всё-таки сделать через import.

**Comment by dzhiriki** [comment]
Импорт в переменную, `jQuery`, а используете `jquery`? Или переменные таки совпадают?
Собственно, в самом шаблоне прописан импорт в `$` и всё работает.
Плагины никакие не используете? Они могут хотеть, чтобы jQuery лежал глобально.

**Comment by felixexter** [comment]
Не все плагины в формате UMD. Для них нужно либо глобальную переменную создавать, либо форкнуть и обернуть в UMD.
