### ISSUE TITLE
В путях лишний слеш

### ISSUE THREAD

**Issue by in-in** [CSSSR/csssr-project-template#57]
В собранном проекте(dist) не подгружаются асеты и фавиконы

![path](https://cloud.githubusercontent.com/assets/8797432/11196705/ad9bff1a-8cc9-11e5-8059-0473097901d2.jpg)
Если убрать лишний слеш в начале проблем нет
Например в стилях:
```jade
link(href='/assets/styles/app.min.css?t=' + timestamp rel='stylesheet')
```
При диплои на GitHub Pages это является проблемой.

**Comment by felixexter** [comment]
Какие пути указывать, решать вам. Это независит от сборки.

**Comment by in-in** [comment]
Немного не понял. Меня устраивают текущие пути, но с ними отображается голый HTML без всего. Я могу конечно руками удалить лишний слеш если вы это имеете в виду.

**Comment by felixexter** [comment]
В демке пути стоят от корня. Если нужны относительно текущего пути, то соответственно убираете слэш. В чём проблема?

**Comment by in-in** [comment]
> В чём проблема?

В недопонимании, наверное.
А зачем так сделано?
Сильно не серчайте на меня я не настоящий сварщик.

**Comment by felixexter** [comment]
Если делать пути относительного текущей страницы, то страницы в поддиректориях будут голыми. Для это и сделаны пути от корня, чтобы страницы отображались.

**Comment by in-in** [comment]
Спасибо
