### ISSUE TITLE
bem-to миксины работают только в том файле где мы подключили bemto.jade

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#59]
Они работают только в том файле где мы подключили bemto.jade.
О проблеме уже известно в issue репы бемту https://github.com/kizu/bemto/issues/42

**Comment by dzhiriki** [comment]
bem-to сейчас подключается в общем лейауте. Если используется этот лейаут,то в файле всё работает. Если лейаут другой, то нужно и в нем подключить. Если совсем без лейауте, то подключать прямо в файл
Увы, у джейда нет возможности подключать какие-то вещи глобально.

**Comment by jt3k** [comment]
Я нашёл способ  подключения в одном месте и использования везде.

**Comment by dzhiriki** [comment]
Какие глобальные переменные? bemto – один джейдовский файл с тремя миксинами.

**Comment by jt3k** [comment]
проблема в том, что эти миксины используют переменные
```
	bemto_settings_prefix
	bemto_settings_element
	bemto_settings_modifier
	bemto_settings_default_tag
	bemto_chain
	bemto_chain_contexts
```
и проблема состоит в том, что данные переменные не видны из миксинов, если миксин используется в другом файле (не там где был подключен bemto).

---
под глобальными переменными я имею в виду проброс их через gulp в качестве объекта переменных темплейта,  как мы делаем это с `getData`, `jv0` и `timestamp`.
