### ISSUE TITLE
Rupture в csssr-project-template

### ISSUE THREAD

**Issue by gearmobile** [CSSSR/csssr-project-template#61]
Объясните, пожалуйста, что означает эта запись:

```css
rupture.mobile-cutoff = 540px
```
С [Rupture](http://jenius.github.io/rupture/) я знаком и в своей практике использую. Но только (*как бы это правильнее сказать*) - в виде отдельных `breakpoints`.

Например, таким образом:

```css
+below(980px)
  .gallery__third > a > span
  .gallery__second > a > span
    font-size 2rem

+below(768px)
  .gallery__third > a > span
  .gallery__second > a > span
    font-size 1.5rem
```

**Comment by dzhiriki** [comment]
Что значит эта запись есть в документации Rupture.
