### ISSUE TITLE
Jade-переменные

### ISSUE THREAD

**Issue by gearmobile** [CSSSR/csssr-project-template#63]
Подскажите, где расположены переменные для jade-шаблонов? Имеются ввиду такие переменные, как (*к примеру*):

```html
- var js = 'javascript:void(0);'
```
Честно искал их в вашем шаблоне, но не смог найти.

**Comment by gitnovikov** [comment]
Здравствуй! Я бы ознакомился с https://github.com/CSSSR/csssr-project-template/blob/master/gulp/tasks/templates.js - прояснит вопрос.

**Comment by gearmobile** [comment]
ок - вопрос снят. Спасибо!
