### ISSUE TITLE
Выложить готовую сборку на сервере

### ISSUE THREAD

**Issue by gearmobile** [CSSSR/csssr-project-template#64]
Сверстал LP с помощью CSSSR-Project-Template - [Brandly](https://github.com/gearmobile/studio/tree/master/brandly).

Сделал `gulp build` для генерации готового кода (для production - я правильно понимаю?).

Выложил содержимое директории `dist` на статический хостинг - [Brandly](https://github.com/gearmobile/brandly).

Пробую открыть страницу в браузере - [Brandly](http://zencoder.ru/brandly/) и получаю совершенно не то, что хочу.

В качестве одной из проблем увидел такую строку в `index.html`:

```html
<link href="/assets/styles/app.min.css?t=1450002711127" rel="stylesheet">
```

Подскажите, в чем причина?

**Comment by felixexter** [comment]
https://github.com/CSSSR/csssr-project-template/issues/57
