### ISSUE TITLE
Импорт css из пакетов node_modules

### ISSUE THREAD

**Issue by yakhinvadim** [CSSSR/csssr-project-template#67]
Всем привет!

Хочу подключить стороннюю библиотеку. Для работы ей нужен свой css-файл.
В текущей версии шаблона (0.12.6) импорт css (не .styl) не работает - эта строка остается в итоговом app.min.css:
`@import '../../node_modules/nouislider/distribute/nouislider.min.css'`

Поискал решение проблемы. Для импорта css, в таске styles нужно дописать эту строчку: 

```
.pipe(stylus({
			(...)
			'include css': true
		}))
```

С ней импорт работает.

Но я сейчас выполняю тестовое задание, и не думаю, что предполагается, что я должен модифицировать шаблон :)

Как подключаются css из сторонних библиотек в текущей версии шаблона?

**Comment by kuflash** [comment]
В принципе все верно сделали. Но можно еще создать отдельный блок где разместить styl файл с нужными стилями для библиотеки

**Comment by felixexter** [comment]
Шаблон на то и шаблон, чтобы он мог меняться в зависимости от твоих нужд.
А вообще просто создаёшь свой блок и вставляешь только необходимые стили.
Ведь тебе явно не жуны же все стили, которые у этого плагина в демке.

**Comment by yakhinvadim** [comment]
Про изменение шаблона понял.

Вставка только необходимых стилей - довольно трудоемкая задача, поэтому хочу именно импортировать.

Обдумал вариант с созданием отдельного блока и пришел к выводу, что самый простой вариант - создать блок со styl-файлом, в котором будет импорт стилей библиотеки.
Вот так: @import '../../../node_modules/nouislider/distribute/nouislider.min.css'

Спасибо за быстрые ответы!

**Comment by felixexter** [comment]
> Вставка только необходимых стилей - довольно трудоемкая задача, поэтому хочу именно импортировать.

Я к тому, что если дизайн твоего слайдера отличается от дизайна демки, то переопредлять стили не лучшая идея. Получается, это тоже самое, что и отдельный блок, только стилей в 2 раза больше в итоговом файле, большинство из которых не используются.

**Comment by frendly** [comment]
А как же тогда быть при обновлении этой библиотеки?
Сравнивать что поменялось?

**Comment by gitnovikov** [comment]
> А как же тогда быть при обновлении этой библиотеки?
> Сравнивать что поменялось? 

Перебивая стили, вероятность появления бага ни меньше чем при варианте о котором писал выше Felix.

**Comment by felixexter** [comment]
@frendly если либа обновится и что-то отвалится, хоть как придётся что-то менять.

**Comment by frendly** [comment]
@gitnovikov @felixexter так вопрос в том, как вы сравниваете версии файлов?

**Comment by felixexter** [comment]
@frendly в репозитории в диффах можно посмотреть, например.

**Comment by yakhinvadim** [comment]
@felixexter 
> Я к тому, что если дизайн твоего слайдера отличается от дизайна демки, то переопределять стили не лучшая идея. Получается, это тоже самое, что и отдельный блок, только стилей в 2 раза больше в итоговом файле, большинство из которых не используются.

1) Я не понял, что ты имел ввиду под фразой  *"получается, это тоже самое, что и отдельный блок"*, можешь пояснить?

2) *"только стилей в 2 раза больше в итоговом файле, большинство из которых не используются"*
в 2 раза больше, это преувеличение, никто не будет переопределять все свойства в css-файле библиотеки. В тестовом задании мне хватило около 10-15 строк чтобы привести слайдер к нужному мне виду, а весь css библиотеки занимает около 200 строк, получается подключение библиотеки импортом и переопределение свойств потребовало увеличить css-код блока на 5-7%. **Это если не использовать минификатор**.

**Если использовать минификатор** из шаблона (clean css), то переопределенные значения будут удалены, за это отвечают следующие функции минификатора:
- mergeAdjacent - merges adjacent rulesets with the same selector or rules;
- reduceNonAdjacent - identifies which properties are overridden in same-selector non-adjacent rulesets, and removes them;

Поэтому с минификатором кода будет столько же.

Есть ли у импорта css-файла библиотеки еще какие-нибудь минусы, кроме тех, которые ты описал?
