### ISSUE TITLE
БЭМ + Jade. Вопросы.

### ISSUE THREAD

**Issue by mrBoombastic** [CSSSR/csssr-project-template#68]
Здравствуйте!

У Вас интересный и удобный шаблон, а БЭМ без адского оверхэда в виде bem-tools вызывает восхищение. Однако, возник ряд вопросов по связке БЭМ + Jade, которые хотелось бы, с Вашего позволения, здесь описать.

1) Судя по демо, у вас принято инклюдить миксин с блоком в страницу или блок, в котором этот миксин используется. Я для своего проекта создал файл `includes-list.jade`, скопом перечислил в нем все свои миксины и заинклюдил его в layout, от которого наследуются остальные страницы. Насколько, по Вашему мнению, такой подход приемлем и каких от него ожидать подводных камней?

2) Для позиционирования блока использую т.н. "микс" (в терминологии Яндекса). В `&attributes` миксина (пускай его имя будет `childBlock`) при вызове передаю класс `parentBlock__childBlock` (где `parentBlock` - имя блока, в который включаю `childBlock` как элемент) и позиционирую `childBlock` внутри `parentBlock` с помощью класса, который создал, можно сказать, "на лету". Опять же, хотелось бы услышать от Вас, насколько адекватно я пользуюсь БЭМ'ом в данном случае.

3) Как я понял, Вы не стилизуете страницы в папке `app/pages`, а создаете дополнительный блок (в демо это `index`) и подключаете его. Получается, что для страницы нужно создавать промежуточный блок, если элементы внутри контентной области страницы требуют дополнительной стилизации (например, позиционирования). Это нужно для того, чтобы избежать перекрытия стилей, которые позиционируют одинаковые блоки на разных страницах?

**Comment by felixexter** [comment]
1. Если подключать сразу всё, то при изменении какого-либо блока будут собираться все страницы, что отразится на времени. Чем меньше глобальных блоков, тем лучше.

2. Вы пользуетесь адекватно настолько, насколько предлагает методология БЭМа. Что касается нас, то мы не пользуемся миксами. Потому что возникает риск переопределения свойств и появляется зависимость от порядка объявленных классов. В разметке же увеличивается длина всех эти классов: допустим, один примиксованный класс ещё терпимо, а если прибавить модификаторы, то это будет совсем не айс.

3. Понятия страницы как в БЭМе, так и у нас в шаблоне не подразумевается, поэтому стилизуются не страницы, а блоки. Сами блоки могут находиться в других блоках. Файлы в папке `app/pages` предназначены только для рендера этих блоков.

**Comment by mrBoombastic** [comment]
Большое спасибо за ответы. С первым и третьим пунктами все стало на свои места. По второму вопросу хотелось бы уточнить: с помощью микса я, фактически, объявляю `childBlock` элементом `parentBlock` и использую новый класс только для позиционирования `childBlock` с помощью стилевого файла, входящего в `parentBlock`. То есть, получается, даже не микс, строго говоря, а просто дополнительный класс для `childBlock`, который в некоторых случаях позволяет избежать использования элемента-обертки `ParentBlock__childBlock-wrapper`.

**Comment by kuflash** [comment]
@mrBoombastic, если я правильно понял, то вы предполагаете использовать классы одного блока типа `block` и `block__elem` на одной ноде, что противоречит БЭМ. Нужно либо использовать микс блока с элементом родительского блока, либо делать что-то типа враппера. Этого мы и придерживаемся, @felixexter об этом как раз и говорит. 

Если привести пример, то будет выглядеть так. Допустим у нас есть блок `form`. А каждое поле этой формы будет тоже отдельным блоком `form-input`. И чтобы можно было удобно располагать эти поля в форме нужно создать такую структуру:

```
.form
  .form__field
    .form-input
  .form__field
    .form-input
```

В данном примере  `.form__field` как раз является враппером блока `form-input` что позволяет удобно орудовать размещением полей в форме и исключает конфликт стилей в зависимости от их расположения в итоговом файле

**Comment by mrBoombastic** [comment]
@kuflash, не могли бы Вы привести пример для позиционирования блока без обертки? Если конкретно, то я, видимо, не совсем понял технику миксования блока с элементом родительского блока. Немного информации удалось найти только здесь: https://ru.bem.info/forum/656/

**Comment by kuflash** [comment]
@mrBoombastic ну по правилам БЭМ микс это когда на одной ноде находятся либо `block-one` и `block-two`, либо `block-one__elem` и `block-two`, но никак не `block-two`  и `block-two__elem` одновременно. Если смотреть по разметке, то вот так нельзя:

```jade
.block-one
  .block-two.block-two__elem
```

А так можно, но мы не используем такой стиль (причину описал  @felixexter )

```jade
.block-one
  .block-two.block-one__elem
```

Мы используем такой вариант

```jade
.block-one
  .block-one__elem
    .block-two
```

**Comment by mrBoombastic** [comment]
@kuflash, я Вас понял. Спасибо.

Хотелось бы еще прояснить, в чем именно заключен риск при использовании микса?

    .block-one
      .block-two.block-one__elem

В том, что мы можем с помощью класса `.block-one__elem` случайно переназначить какие-то из свойств, указанных для `.block-two`? Мне кажется, если разграничить зоны ответственности этих двух классов (`.block-two` отвечает за "внутреннее" состояние блока - паддинги, размеры, позиционирование внутренних элементов, а `.block-one__elem` - за "внешнее" - position, margin, float), то эта проблема утратит свою актуальность.

Опять же, хочу подчеркнуть, что использование миксов в том виде, в каком это делает Яндекс, мне не нравится так же, как и Вам. Они проблему переопределения (которая обязательно возникает, поскольку миксам позволено изменять любые свойства блока) решают с помощью костылей, двигая классы в итоговом css, что, безусловно не интересно тем, кто не пользуется bem-tools. Мне интересна концепция отказа от оберток, в тех случаях, где их функционал (речь, конечно же о позиционировании блока) можно получить, просто используя дополнительный класс для блока.

**Comment by kuflash** [comment]
В целом все верно. Если элемент родителя будет только заниматься позицией и отступами, то можно отказаться от обертки и сделать микс.

**Comment by mrBoombastic** [comment]
По связке БЭМ + Jade пока не очень много материалов в сети, поэтому, Ваш опыт по созданию удобного рабочего окружения, можно сказать, уникален. Большое спасибо за обстоятельные разъяснения))

**Comment by kuflash** [comment]
Пожалуйста. Если вопросов больше нет, то issue закрываем?

**Comment by mrBoombastic** [comment]
Да, можно закрывать.
