### ISSUE TITLE
Не генерирует javascript

### ISSUE THREAD

**Issue by Ivanopalas** [CSSSR/csssr-project-template#71]
Здравствуйте!
Столкнулся с такой проблемой что весь javascript код который Я пишу в блоки он игнорирует и не обрабатывает. С jade и stylus нет проблем, все работает хорошо и результат комплита выводиться в терминал. Что нельзя сказать про js файлы, такое впечатление что сборщик их просто не видит, При сохранении не выводит ничего в терминал. Help me please!!)

**Comment by Nitive** [comment]
Нужно импортировать их в [`app/scripts/app.js`](https://github.com/CSSSR/csssr-project-template/blob/master/app/scripts/app.js)

**Comment by Ivanopalas** [comment]
import ../blocks/myblock/myblock  - Так?

**Comment by Nitive** [comment]
`import '../blocks/myblock/myblock.js';` или `require('../blocks/myblock/myblock.js');`

**Comment by Ivanopalas** [comment]
Спасибо, все получилось!

**Comment by Nitive** [comment]
И всё-таки почитайте про commonjs модули :wink:

**Comment by felixexter** [comment]
В сборке настроены пути относительно `app`, так что можно просто положить `index.js` в `blocks/myblock` и вместо 

```javascript
import '../blocks/myblock/myblock.js';
```

подключать вот так:
```javascript
import 'blocks/myblock';
```

**Comment by TryHardNinja** [comment]
Подскажите почему плохо подключать по маске аля 'app/blocks/**/*.js' ?

**Comment by Nitive** [comment]
@TryHardNinja Неочевидный порядок файлов, неочевидные зависимости
