### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by iamstarkov** [CSSSR/csssr-project-template#80]
Можно было бы добавить такой файл в репозиторий с руководством по созданию пулл-реквестов и созданию ишью, чтобы было меньше неотёсанных ишью и больше заранее обсужденных пулл-реквестов

**Comment by felixexter** [comment]
@iamstarkov [Держи](https://github.com/CSSSR/csssr-project-template/blob/master/contributing.md), товарищ :)

**Comment by iamstarkov** [comment]
но… там не слова про ишью и пулл-реквесты

**Comment by felixexter** [comment]
Что ты ожидал увидеть?

**Comment by iamstarkov** [comment]
1. инструкцию по заведению ишью (когда, зачем + reproduce steps)
2. как правильно сабмитить пулл-реквест. первое, что я вижу попросить заводить ишью, чтобы обсудить идею пулл-реквеста и чтобы посмотрели делали ли похожее раньше

**Comment by in-in** [comment]
@iamstarkov Я хочу в файле `app/blocks/index/index.jade` исправить `.index__group` на `+e.group`.
Заводить ишью сначала слишком накладно получается для всех - повода к обсуждению нет.

**Comment by iamstarkov** [comment]
инструкция и обсуждение пулл-реквестов помогла бы избежать таких пулл-реквестов: #79 #81

**Comment by iamstarkov** [comment]
а просьба использовать гугл и стековерфлоу перед созданием ишью помогла бы избегать таких простых ишью как #74

**Comment by felixexter** [comment]
@iamstarkov Понял тебя, сейчас обновлю.

**Comment by felixexter** [comment]
@in-in Т.к. этот элемент находится внутри другого блока `.content`, то класс в итоге получится не ожидаемый `.index__group`, а `.content__group`. Стоит это учитывать, когда пользуешься [bemto](https://github.com/kizu/bemto).

**Comment by iamstarkov** [comment]
@felixexter оффтопик: вы пробовали использовать внешний purejs генератор классов? типа [b_](https://www.npmjs.com/package/b_) достаточно прокинуть в locals к jade

**Comment by felixexter** [comment]
@iamstarkov Только в реакте и совершенно похожие аналоги [`classnames`](/JedWatson/classnames), [`bem-cn`](/albburtsev/bem-cn) и [`css-modules`](/css-modules/css-modules).

**Comment by felixexter** [comment]
Здесь в принципе тоже можно, но минус только в том, что больше кода, чем это было бы с bemto.

**Comment by felixexter** [comment]
@iamstarkov Обновил.

**Comment by iamstarkov** [comment]
чуть больше кода, зато больше гибкости и джаваскрипт легче дебажить чем jade-расширение

**Comment by iamstarkov** [comment]
посмотрел обновлённую версию. всё круто

**Comment by iamstarkov** [comment]
кхм, только оказывается лейблы могут использовать только оунеры и коллабораторы проекта. поэтому сторонний человек при создании ишью не может делать этого

**Comment by iamstarkov** [comment]
гратц!

**Comment by felixexter** [comment]
Про лэйблы тогда в скобках укажу, что это могут только оунеры.

**Comment by iamstarkov** [comment]
лучше мне кажется совсем тогда удалить, так как этот файл не для них
