### ISSUE TITLE
Обновление конфига для csscomb

### ISSUE THREAD

**Issue by in-in** [CSSSR/csssr-project-template#82]
В файле .csscomb.json не хватает несколько свойств:
justify-content, flex-wrap, flex-flow и другие из флексовой группы. Так же аnimation-fill-mode.
Возможно, не уверен, какие-то свойства устарели - flex-pack (не знаю что это).

**Comment by Nitive** [comment]
Csscomb когда-то был нужен для причёски скомпилированного css. Это уже давно не требуется, предлагаю вообще выпилить csscomb.
К тому же можно линтить stylus с помощью [stylint](https://github.com/rossPatton/stylint)

**Comment by jt3k** [comment]
csscomb очень полезен для причёсывания не скомпилированных файлов scss sass less и др.
К сожалению csscomb не умеет в stylus :(

**Comment by felixexter** [comment]
Да, CSSComb нужно выпилить. Форматирвоать имеет смысл только исходники.
