### ISSUE TITLE
Не могу запустить новый проект

### ISSUE THREAD

**Issue by akhalizev** [CSSSR/csssr-project-template#87]
Система OsX10.11, node 5.6.0, npm 3.6.0.
Видимо ошибка с babel, была подобная ветка #85, но там проект запускался.
Вот, что выводит консоль https://gist.github.com/akhalizev/7701933574b177ff2a81

**Comment by dzhiriki** [comment]
gulp обновил зависимости и хочет babel@6, в то время как у нас еще используется babel@5. Обновим у себя зависимости в ближайшее время.
Сейчас, как быстрый вариант, можно поставить версию галпа постарее. 
Например: `npm i gulp@3.9.0`

**Comment by iamstarkov** [comment]
```
$ npm i -g generator-babel
$ yo babel es2015
```
добавит необходимые для babel@6 зависимости
