### ISSUE TITLE
Классы/миксины для сокрытия элементов на странице

### ISSUE THREAD

**Issue by riseremi** [CSSSR/csssr-project-template#93]
Привет!

Думали ли вы когда-нибудь сделать миксины в духе `hide-on-mobile()` и `hide-on-desktop()` для более удобной адаптивной вёрстки? Такое есть в [Unsemantic Grid](http://unsemantic.com/css-documentation#4-mobile-amp-hidden-classes), но на уровне классов. Если думали, но решили не делать, то почему?

Спасибо.

**Comment by jt3k** [comment]
@riseremi  Привет. Дык ведь есть уже [руптуре](http://jenius.github.io/rupture/) зачем ещё одну?

**Comment by riseremi** [comment]
Чтобы в Jade/HTML можно было проставить `.hide-on-mobile` нужным блокам/элементам, не трогая стили. Плохая практика?

**Comment by dzhiriki** [comment]
Миксины — это как раз rupture.
Классы — да, плохо. Потому что классы не должны отображать стили, а должны отображать суть элемента. Т.е. быть cемантически корректными.
Собственно, ничего не мешает на конкретном проекте завести эти классы, если хочется.

**Comment by riseremi** [comment]
Понял, тогда вопрос снят. Спасибо.
