### ISSUE TITLE
Не обновляются .json файлы

### ISSUE THREAD

**Issue by akhalizev** [CSSSR/csssr-project-template#94]
Возникла проблема с изменением source-tree.json и tools.json. Попробовал изменить их с только что скачанного репозитория, изменений система не видит. Даже простую замену одного текста на другой.

**Comment by gitnovikov** [comment]
Здравствуй, попробуй "перезапустить" проект.

**Comment by akhalizev** [comment]
Да, обнаружил, что нужно форсировать обновление страниц, изменив что-нибудь в любом jade файле.
Чтобы каждый раз проект не перезапускать.

**Comment by gitnovikov** [comment]
Насколько помню данный темплейт не следит за изменениями json и не видит (до перезапуска) созданные файлы.

**Comment by iamstarkov** [comment]
обновите вотч под свои нужды

**Comment by felixexter** [comment]
Только вотч один не поможет. В templates стоит кэширование, которое не включает json. Можно убрать кэширование, чтобы обновлялось, но без него, если будет много страниц, будет дольше собирать.
Если кто знает, как сделать кэширование jade и json вместе, пулреквест приветствуется :)
