### ISSUE TITLE
Замечания по make-blocks

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#95]
Поверстал я часок с новым make-block. Получается намного быстрее верстать!
Но есть несколько неприятных моментов:
1. Приходится постоянно писать руками `include blocks/new-block/new-block` в тех местах где хотим заюзать блок. 
Посему вопрос: Встречали ли вы плагины которые позволяли бы приинклюдивать сразу все миксины из определённой папки. Ведь это стало бы киллер-фитчей нашего шаблончика :)
2. При создании блока мы получаем jade-разметку примерно такого вида (см ниже), в ней очень не хватает ключевого слова block. 

```
mixin {blockName}()
    +b.{blockName}&attributes(attributes)
        | {blockName}
                block //- вот сюда 
```

Потому-что когда мы делаем много вложенных друг в друга блоков то постоянно приходится добавлять это ключевое слово в каждый новый блок.
Этот `block` ни на что не влияет. Давайте добавим ? :)

**Comment by jt3k** [comment]
Гы! Кажется по первому вопросу я нашёл! https://github.com/KellyLSB/jade-glob-include
 Я попробую заюзать это завтра, и если проканает подготовлю ПР

**Comment by felixexter** [comment]
Сразу всё инклудить плохая примета. Явное объявление лучше неявного.
Если всё подключить в каждый блок, время сборки будет увеличиваться.
Но можно оптимизировать сам импорт других блоков.
Т.к. в основном подключаются блоки из папки blocks, то для начала можно указать корневую папку в blocks.
Путь с
`include blocks/new-block/new-block`
сократится до
`include /new-block/new-block`.
Осталось решить последний нюанс, как сделать аналогично шаблонам в express, чтобы лежащий файл `/new-block/index.jade` в подключался без его указывания.
Так можно бы сократить с
`include /new-block/new-block`
до
`include /new-block`.

**Comment by jt3k** [comment]
дык. никакого неявного действия та штука не делает. Она  всего лишь добавляет возможность делать [glob-синтаксис  в инклудах](https://github.com/KellyLSB/jade-glob-include#how-does-this-change-include)

**Comment by jt3k** [comment]
Я нашёл [более модную штуку](https://github.com/CREEATION/gulp-jade-globbing),  на тему глобов в инклюдах! 
, и уже успел попробовать. Это атас! %) 
В проекте 60 блоков разной сложности. 
Приинклюдиваю сразу всё содержимое папки `app/blocks/**/*.jade`
 инклюдится и отрабатывает меньше чем за секунду! :+1: 

стоит попробовать!

**Comment by dzhiriki** [comment]
В шаблоне используется `gulp-jade-inheritance`, который фильтрует измененные страницы, чтобы реально пересобирать только то, что изменилось.
Т.е. если мы изменили один блок, то пересоберутся лишь страницы, на которых этот блок использовался.
В случае с глобами, такой способ работать не будет, ибо на страницу подключаются все блоки => при изменении любого блока страница будет пересобираться, что на больших проектах очень плохо.

**Comment by jt3k** [comment]
Не совсем понял что ты написал. то есть сейчас собираются не все блоки ? Это как ?

Допустим в директории 999 блоков.
Я их все подключаю в своём джейд-файле руками на 999 строчках.
теперь когда я меняю  чтото в одном из этих 999 файлах у меня произойдёт пересборка только этого 1 файла?

Звучит как фантастика.

Сейчас почитаю что делает gulp-jade-inheritance

**Comment by dzhiriki** [comment]
Мы меняем блок => пересобираются только страницы на которых этот блок подключается.
Мы на странице подключаем все блоки глобом => при изменении _любого_ блока страница пересобирается.

**Comment by jt3k** [comment]
а вы проверяли ?

**Comment by dzhiriki** [comment]
Что проверять?
В gulp-jade-inheritance попадает измененные файлы. Он выдает те файлы, которые инклюдят этот блок. И их уже пересобираем.
Определение происходит именно по инклюдам \ экстендам. Берем измененные файлы, смотрим куда они инклюдятся и так далее по всей цепочке (файлы, где инклюдится блок, в котором инклюдится измененный блок).
Если будут глобы, то как будет работать определение? Никак не будет. Никак не определить от каких блоков зависит тот или иной блок.

**Comment by jt3k** [comment]
в inheritance не попадает исходный джейд файл. как глобы могут мешать ?

**Comment by dzhiriki** [comment]
Есть два блока. А и Б.
На странице используется только блок А, но глобом подключаются _оба_.
Поэтому при изменении блока Б, страница будет пересобираться.
Потому что этот блок на страницу подключается из-за глоба.

**Comment by jt3k** [comment]
чтобы этого не происходило и используется inheritance  разве нет ?

**Comment by dzhiriki** [comment]
Он определяет зависимости по инклюдам. Мы инклюдим все файлы. 
=> определение работать не будет.

**Comment by jt3k** [comment]
Хм. Ты хочешь сказать, что смысла не будет в этом определении т.к. инклюдятся все-привсе джэйды?
и
не отрицаешь того, что если мы все файлы будем инклюдить руками то получим тот же эффект ?

**Comment by dzhiriki** [comment]
Если инклюдить все файлы, то да, определение не будет работать. По причине описанной выше
Но мы не инклюдим все файлы. А инклюдим только те, что реально используются.

**Comment by in-in** [comment]
Вообще, время сборки Jade удручает. В app/pages/ находится несколько страниц и компиляция занимает 3 секунды. Хочется увидеть архитектуру большого проекта на этом шаблоне.

**Comment by jt3k** [comment]
ок. ясно. понятно.

значит подведём итог:
1. По первому вопросу в первом посте:
  После создания нового блока мы выводим на экран сообщение(обсуждаемый вариант)
```
  0. был создан миксин для блока new-block
  1. Вставьте его в вашу страницу include blocks/new-block/new-block
```
Такой вариант позволит просто скопировать и вставить один раз

2. По второму вопросу в первом посте ни у кого возражений нет?

**Comment by dzhiriki** [comment]
1. На мой взгляд, сообщение про инклюд  досатточно бессмысленное, потому что копировать из консоли неудобно. А для быстрого набора есть сниппеты. Соответственно, пользоваться этим мало кто будет.
2. Не все миксины принимают блок, не во всех миксинах будет блок на первом уровне. Но, в целом, я бы добавил, потому что удалить эту строчку быстрее, чем написать и двигать строчку тоже можно. Только не после текста с именем блока, а вместо него. Это смотрелось бы логичнее.

**Comment by jt3k** [comment]
млн. 
по поводу пункта 2:
вместо текста считаю будет  плохо.  Так написав инклюд (и миксин) в джейд-файле мы сразу видим имя блока в разметке(не надо лезть в дев-тулзу и смотреть добавился ли блок...)

иначе можно даже и не заметить ошибку и продолжить писать разметку
я бы оставил, потому что удалить эту строчку быстрее, чем написать

**Comment by jt3k** [comment]
Коллеги я пока закрываю этот ишьюс. 
(для себя я уже давно сделал автоинклюд джейд-файлов и счастливо живу)
