### ISSUE TITLE
подключение svg4everybody.legacy

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#96]
Возник вопросик.
В [документации](https://github.com/jonathantneal/svg4everybody) пишут что для поддержки ие6-8 нужно подключить специальный файлик "svg4everybody.legacy.js"

Посоветуйте как мне это сделать внутри /scripts/app.js. Либо другим способом.

**Comment by Nitive** [comment]
`import 'module'` – импортировать файл `./node_modules/module/<main>`, где <main> содержимое поля "main" в `package.json` модуля.
`import 'module/file.js'` – импортировать файл `./node_modules/module/file.js`

**Comment by Nitive** [comment]
На самом деле он не только в `./node_modules/` ищет, а в `$PATH`

**Comment by jt3k** [comment]
ок спс
