### ISSUE TITLE
Как работать с svg4everyone в ие 8 ?

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#97]
при запуске legacy-версии , как сказано в их мануале происходит ошибка ![](https://i.imgur.com/7ta4sbG.png)

как это дебажить в ие я хз, посему второй вопрос: где отключить сорцмапы ?

**Comment by Nitive** [comment]
Где включить? `npm start -- --sourcemaps`

**Comment by azanov** [comment]
В readme svg4everybody указано:

> IE 6-8 require you to put the script in the <head> in order to shiv <svg> and <use> elements.

Подключение в app.js не вариант, так как он цепляется перед  `</body>`

**Comment by jt3k** [comment]
ок, перед  боди повесил. переиминовывает пути, ок. а оно должно рендерить в png само или я должен  рендерить заранее ?

**Comment by jt3k** [comment]
то есть я должен буду сформировать фоллбэчные png-картинки заранее или  этот шаблон  умеет их формировать сам без моего участия ?

**Comment by jt3k** [comment]
BUMP UP
