### ISSUE TITLE
Как работать с svg4everyone в ие 8 ?

### ISSUE THREAD

**Issue by jt3k** [CSSSR/csssr-project-template#98]
сабж

**Comment by dzhiriki** [comment]
Что именно делает svg4everyone для ие8 написано в ридми svg4everyone.
Он заменяет <svg> на картинки с сылкой до png. Ссылка формируется в зависимости от ссылки до свг.
Автоматического конвертирования свг в пнг в шаблоне нет.

**Comment by jt3k** [comment]
UPD свг-фор-эвриван не умеет рендерить в пнг. а жаль.
