### ISSUE TITLE
Странное поведение stylint

### ISSUE THREAD

**Issue by yustnip** [CSSSR/csssr-project-template#99]
Создаю блок .blog-header и к нему пишу стили.
```
.blog-header
    &__title
        font-size 35px
        font-weight 700
```

При сохранении stylint ругается, что глубина селектора больше 5, что явно не так.

```
app/blocks/blog-header/blog-header.styl
  line 2:  selector depth greater than 5  &__title
  line 3:  selector depth greater than 5  font-size 35px
  line 4:  selector depth greater than 5  font-weight 700
```

**Comment by jt3k** [comment]
с этим линтером беда. По всей видимости его никто не настраивал, он ругается даже на порядок свойств :( я просто забил на него

**Comment by yustnip** [comment]
Ну на порядок свойст он и натравлен ругаться. :)

**Comment by sneizdecker** [comment]
Цитата отсюда:
https://github.com/CSSSR/sputnik/blob/master/Stylus.md

> Используйте табы для отступов, не используйте табы и пробелы одновременно - стили не скомпилируются.

Скорее всего, проблема в этом.

**Comment by jt3k** [comment]
Раньше юзил scss и csscomb мне после каждого сохранения сам сортировал свойства в scss-файле. 
Руками их сортировать нет никакого смысла, т.к. затрачивается уйма времени на это.

Лучше бы оно просто сообщало о таких вещах как float-left и position-absolute в одном блоке, и всё.

**Comment by in-in** [comment]
@yustnip Чтобы использовать пробелы я редактировал `.editorconfig` и `.stylintrc` ("indentPref": 2) если 2 пробела. Stylint перестал ругаться.

**Comment by pavel-yagodin** [comment]
@jt3k не надо руками https://github.com/Nitive/sublime-stylint-sorting

**Comment by jt3k** [comment]
Гран-мерси! Круто )

**Comment by yustnip** [comment]
Ложная тревога, все нормально. Редактор заглючил и смешал мне табы с пробельными отступами, отединообразил все и стало хорошо. Всем спасибо!
